### ISSUE TITLE
climatology shifted for objects not starting on January

### ISSUE THREAD

**Issue by OskarMETNO** [metno/esd#100]
I get a shifted output when using climatology() on time series that do not start on January.

Here is an example:
`data(ferder)`
`plot(climatology(subset(ferder,it=1:40000))) # use the first 40 000 data points`
`lines(climatology(subset(ferder,it=181:40180))) # use the same amount of points, but starting roughly half a year later`
![ferder-climatology-error](https://cloud.githubusercontent.com/assets/10518039/8618030/3dd2d1ba-270a-11e5-9997-5f4a78dc9f52.png)

**Comment by abdelkaderm** [comment]
Try now, I think I fixed the problem :+1:
