### ISSUE TITLE
Function "tim.colors" not found

### ISSUE THREAD

**Issue by OskarMETNO** [metno/esd#101]
I am pretty sure this function used to be included, but now it cannot be found.
Example:
`data(eof.t2m.DNMI)`
`image.plot(eof.t2m.DNMI)`
Gives the following error:
`Error in image.default(..., add = add, col = col) : `
`  could not find function "tim.colors"`
`Error in image.default(..., add = add, col = col) : `
`  could not find function "tim.colors"`

**Comment by OskarMETNO** [comment]
Silly me. Actually, it seems it's in the 'fields' package. I just loaded 'fields' and it worked obviously. Should 'fields' be a requirement for 'esd' so that it loads at the same time or is there a clever way to note that the image.plot function is depending on fields without making the whole esd package depend on it?

**Comment by abdelkaderm** [comment]
Hi !
Please use the function `map` instead which uses `image.plot` function from the field object with specific default values required in **esd**. All colour bar arguments are specified as a list in `colbar` argument. To get the full list of arguments when mapping a `field` object., try 
```r
args(map.field)
```
which will produce the following 
>
function (x, FUN = "mean", it = NULL, is = NULL, new = FALSE, 
    projection = "lonlat", xlim = NULL, ylim = NULL, zlim = NULL, 
    n = 15, colbar = list(pal = NULL, rev = FALSE, n = 10, breaks = NULL, 
        type = "p", cex = 2, show = TRUE, h = 0.6, v = 1, pos = 0.05), 
    type = c("fill", "contour"), gridlines = FALSE, lonR = NULL, 
    latR = -90, axiR = NULL, verbose = FALSE, na.rm = TRUE, ...)
