### ISSUE TITLE
Error in opening 4 dimension file of NCEP/NCAR

### ISSUE THREAD

**Issue by monamidutta** [metno/esd#104]
I am trying to open a file in esd (new version) from NCEP/NCAR reanalysis which has 4 dimension (lon,lat, time and vertical levels),
geo <- retrieve.ncdf4("hgt.mon.mean.nc",time=c(1979,2000),lon=c(60,97),lat=c(8,37))
 its giving error:
Error in R_nc4_get_vara_double: NetCDF: Start+count exceeds dimension bound
Var: hgt  Ndims: 4   Start: 0,16,22,24Count: 804,17,11,15
Error in ncvar_get_inner(idobj$group_id, idobj$id, nc$var[[li]]$missval,  : 
  C function R_nc4_get_vara_double returned error

How to fix it???

Though i am able to open it in R, outside esd environment

**Comment by abdelkaderm** [comment]
Hi Monami,
You cannot get all levels in retrieve, but what you can do, is to specify one level at a time, the reason is that the output of retrieve must be a 3D, try this 
```r
geo <- retrieve.ncdf4("hgt.mon.mean.nc",time=c(1979,2000),lon=c(60,97),lat=c(8,37),level=1)
```

**Comment by javakh** [comment]
I have tried this but not working:
> ncp1<-retrieve.ncdf4('D:/shum.mon.mean.nc',lat=c(6,40),lon=c(60,100),lev=1)
Error in val[lon.srt, , , ] : incorrect number of dimensions

**Comment by abdelkaderm** [comment]
Hi there, 
Please reinstall the package and try it again, should be working now. Remember that esd-package deals with one level pressure at a time. The correct syntax must be like
```r
geo <- retrieve("hgt.mon.mean.nc",time=c(1979,2000),lon=c(60,97),lat=c(8,37),lev=1000)
```

**Comment by abdelkaderm** [comment]
Please visit our News page for recent updates at
https://github.com/metno/esd/wiki/00.News/_edit
