### ISSUE TITLE
Downscaling over gridded observational data instead of station data

### ISSUE THREAD

**Issue by javakh** [metno/esd#105]
Hello,

I'm working with Gridded observational(for precipitation) data (0.25x0.25) as station data not available for the study region.I have converted the gridded data to station data using as.station() following Dr. Mezghani's advice.But now I'm facing several problems.

Firstly, the observational data has 'NA' values over sea-region and regions outside country (India) border.Therefore PCA() function is not working.

secondly, about choosing predictor. As I have enormous no. of grid points (over 1000) it is not possible to select predictors for individual grid points. What to do in this case???

thirdly,I have selected a smaller region where no 'NA' values present and chosen an arbitrary predictor (SLP) and try to do DS with PCA of grid points and EOF of selected predictor and getting the following error.

Error in `[<-`(`*tmp*`, is.finite(ys), i, value = c(-0.0811400559129424,  : 
  (subscript) logical subscript too long

Therefore, i'm unable to proceed further.

Please help me to find a solution.

Thanks.
-Javed Akhter

**Comment by abdelkaderm** [comment]
Hi there, 

What you can do is to keep inland grid cells only. to do so, you need to use a mask. In the `esd-package` 

First, we have stored a 5m elevation data object called `etopo5`. Please type 
```r
## Load the data object into your R open session. 
data(etopo5)
## Extract area covering India like
etopo5.india <- subset(etopo5,is=list(lon=c(50,100),lat=c(0,50)))
## Convert etopo5.india into a field object as
d <- dim(etopo5.india)
dim(etopo5.india) <- d[1]*d[2]
etopo.zoo <- zoo(t(etopo5.india),order.by=1:2)
## convert as field as
etopo5.india <- as.field(etopo.zoo,lon=attr(etopo5.india,'longitude') ,lat=attr(etopo5.india, 'latitude') ,param='elevation',unit='m')
## display the map
map(etopo5.india)
```
Second, use `regrid` to regrid the latter into the observational grid (i.e. 0.25x0.25) such as
```r
## New grid coordinates
xn<-seq(50,100,by=0.25)
yn<-seq(0,50,by=0.25)
etopo5.india.new <- regrid(etopo5.india,is=list(lon=xn,lat=yn))
```
Third, extract inland grid cells only as 
```r
## Replace offland data with NA
coredata(etopo5.india.new)[coredata(etopo5.india.new)<0] <- NA 
map(etopo5.india.new)
etopo5.india.inland <- etopo5.india.new[!is.na(etopo5.india.new)]

*NEED to review a bit point 3 !*
