### ISSUE TITLE
esd package problem

### ISSUE THREAD

**Issue by avikdas91** [metno/esd#106]
i am working in "esd package" in "R" version 3.2.1,esd version 0.9-6 in windows 8.1 pro.I have found a problem when i was retrieving a file mentioning a time boundary.
>test=retrieve("D:/ncfiles/pcmdi.ipcc4.cnrm_cm3.20c3m.run1.monthly.tas_A1.nc",lat=c(6,40),lon=c(60,97),time=c(1950,1960))
Choose variable lon_bnds/lat_bnds/time_bnds/height/tas(from 1 - 5): 5
""Warning : Calendar attribute has not been found in the meta data".
now the problem is as i mentioned the time boundary from 1950-1960, it fails to retrieve that part from the file.it was retrieving the whole time zone from the file.
how to fix this error?plz help

**Comment by abdelkaderm** [comment]
Dear, 
I think you are running an old version of retrieve, the argument `time` has been replaced by the argument `it` in `retrieve` function.

The correct syntax is the following
` test=retrieve("D:/ncfiles/pcmdi.ipcc4.cnrm_cm3.20c3m.run1.monthly.tas_A1.nc",lat=c(6,40),lon=c(60,97),it=c(1950,1960))
`

**Comment by abdelkaderm** [comment]
Please visit our News page for recent updates ...
https://github.com/metno/esd/wiki/00.News/_edit
