### ISSUE TITLE
Getting error in corfield function

### ISSUE THREAD

**Issue by javakh** [metno/esd#107]
I'm trying to correlate field data with station data using corfield function. Now when I'm using reanalysis data as gridded data it is working fine. But when the gridded data GCM data it is producing the map on the screen but also giving the following error:

> cr2<-corfield.station(st2,gcm1_june)
Error in text.default(lon[1], lat[1] - dlat, sub, col = "grey30", pos = 4,  : 
  zero-length 'labels' specified

here st2 is the station data for june month,gcm1_june gridded data for june. 
Time period is same for both.

Please help in this matter.

Thanks.

**Comment by abdelkaderm** [comment]
Hi there, 
`corfield` should be working properly, please check that variable names and attributes were set correctly in both station and gcm objects.
Best,
