### ISSUE TITLE
Getting error ('logical subscript too long')while running DS

### ISSUE THREAD

**Issue by javakh** [metno/esd#108]
I'm trying to downscale PCA of 36 observed time series with one predictor for calibration and validation period as follows:
>obs<-subset(pr_sub_ind,it=c(1961,2005))
>pc<-PCA(obs)
>cal1<-subset(shum500,it=c(1961,1990))
>val1<-subset(shum500,it=c(1991,2005))
>comb1 <- combine(cal1,val1)
>eof1_june<-EOF(comb1,it='june')
> ds1_june<-DS(pc,eof1_june)
                                                                          
  |====                                                                  |   5%Error in `[<-`(`*tmp*`, is.finite(ys), i, value = c(0.0649790135963084,  : 
  (subscript) logical subscript too long

And process is stopping there. I have also used DS.pca ().But the result is same.
However,if i take single station data instead of PCA object,it is working fine.
structure of PCA object is 
> str(pc)
‘zoo’ series from 1961-01-01 to 2005-12-01
  Data: num [1:540, 1:20] -0.0343 -0.032 -0.0364 -0.0298 0.0129 ...
 - attr(*, "dimnames")=List of 2
  ..$ : NULL
  ..$ : chr [1:20] "X.1" "X.2" "X.3" "X.4" ...
 - attr(*, "station_id")= int [1:36] 1 2 3 4 5 6 7 8 9 10 ...
 - attr(*, "variable")= chr [1:36] "pr" "pr" "pr" "pr" ...
 - attr(*, "unit")= chr [1:36] "mm" "mm" "mm" "mm" ...
 - attr(*, "calendar")= chr "gregorian"
 - attr(*, "timeunit")= chr "month"
 - attr(*, "history")=List of 3
  ..$ call     :List of 2
  .. ..$ : language PCA.station(obs)
  .. ..$ : language station.subset(x, it = it, is = is, verbose = verbose)
  ..$ timestamp: chr [1:2] "Wed Aug 12 13:00:48 2015" "Wed Aug 12 13:00:37 2015"
  ..$ session  :List of 6
  .. ..$ R.version  : chr "R version 3.1.1 (2014-07-10)"
  .. ..$ esd.version: chr "esd_0.9-6"
  .. ..$ platform   : chr "x86_64-w64-mingw32/x64 (64-bit)"
  .. ..$ R.version  : chr "R version 3.1.1 (2014-07-10)"
  .. ..$ esd.version: chr "esd_0.9-6"
  .. ..$ platform   : chr "x86_64-w64-mingw32/x64 (64-bit)"
 - attr(*, "pattern")= num [1:36, 1:20] 0.169 0.25 0.142 0.145 0.135 ...
 - attr(*, "dimensions")= int [1:2] 36 540
 - attr(*, "mean")= Named num [1:36] 196 232 130 118 105 ...
  ..- attr(*, "names")= chr [1:36] "ANDAMAN and NICOBAR ISLANDS" "ARUNACHAL PRADESH" "ASSAM & MEGHALAYA" "NAGALAND-MANIPUR-MIZORAM-TRIPURA" ...
 - attr(*, "max.autocor")= num 0.795
 - attr(*, "eigenvalues")= num [1:20] 19285 4901 4457 3819 2789 ...
 - attr(*, "sum.eigenv")= num 67367
 - attr(*, "tot.var")= num 4.84e+08
 - attr(*, "aspect")= chr "anomaly"
  Index:  Date[1:540], format: "1961-01-01" "1961-02-01" "1961-03-01" "1961-04-01" "1961-05-01" "1961-06-01" "1961-07-01" "1961-08-01" "1961-09-01" "1961-10-01" ...

Please help in this matter.
Thanks.

**Comment by abdelkaderm** [comment]
Hi Javed, 
Can you use the function trace() to trace back where the process stopped. Try the following and copy and send me what you get
```r
trace(ds1_june<-DS(pc,eof1_june))
traceback()
```

Also, I do not understand why you split the data in cal1 anf val1 and then computed the EOF on combined eof comb1? YOu have to combine GCM with reanalysis data ! The problem here is that 'esd' see the comb1 as a combination between REA and GCM which is not the case !

Have you tried `eof1_june<-EOF(shum500,it='june')`

**Comment by javakh** [comment]
Actually I want to split the whole data set in two periods-one for calibration (1961,1990) and other for validation (1991,2005).
I found an example in 'esd' pdf where calibration and validation period are combined before downscaling. That's why I'm combining both.
This is the example:(page 22 in 'esd' pdf)
"# part of the record and use the other part for evaluation.
T2M <- as.annual(t2m.NCEP(lon=c(-10,30),lat=c(50,70)))
cal <- subset(T2M,it=c("1948-01-01","1980-01-01"))
pre <- subset(T2M,it=c("1981-01-01","2013-01-01"))
comb <- combine(cal,pre)
X <- EOF(comb)
data(bjornholt)
y <- as.annual(bjornholt,FUN="exceedance")
z <- DS(y,X)
plot(z)
"

I'll send the results of trace() to you as soon as possible.

**Comment by abdelkaderm** [comment]
ok got it !

**Comment by javakh** [comment]
Results from trace()


> trace(ds1_june<-DS(pc,eof1_june))

  |                                                                            
  |                                                                      |   0%
  |                                                                            
  |====                                                                  |   5%Error in `[<-`(`*tmp*`, is.finite(ys), i, value = c(0.0507691810445544,  : 
  (subscript) logical subscript too long
> traceback()
3: DS.pca(pc, eof1_june)
2: DS(pc, eof1_june)
1: trace(ds1_june <- DS(pc, eof1_june))

**Comment by abdelkaderm** [comment]
Hi Jitendra,

I cannot remember, did you send me the data of your example somewhere ? We have made few changes and I would like to run it again. thanks
