### ISSUE TITLE
error while plot(cca)

### ISSUE THREAD

**Issue by monamidutta** [metno/esd#109]
> pca_jan <- PCA(stn_jan)  # pca of stations in Himalaya for January month
> plot(pca_jan)
> eof <- EOF(t2m_jan)     # eof of january of 2 meter air temp from eraint
> cca <- CCA(pca_jan,eof)
[1] "CCA.pca"
[1] "CCA.eof"
[1] "Barnett-Preisendorfer CCA"
> plot(cca)
Error in rbind(attr(x, "pattern")[, pattern], attr(x, "pattern")[, pattern]) : 
  object 'icca' not found

but there are values in object cca

Help me in this matter

**Comment by abdelkaderm** [comment]
I have made q quick fix now, but still need to work on the visualisation, sth is wrong with the margins !
