### ISSUE TITLE
cyclone identification

### ISSUE THREAD

**Issue by kajsamp** [metno/esd#110]
I'm implementing and testing the cyclone identification method (CCI) and have run into a problem. 

This is how the method works: 1) Pressure profiles in the north-south (NS) and east-west (EW) direction are represented as Fourier approximations. 2) The first and second derivatives are calculated based on the Fourier series. 3) Pressure minima are identified as points where the first derivative is 0 and the second derivative is positive both in the NS and EW direction. 4) Secondary cyclones that are located close to other deeper cyclones are removed. 

The problem comes in when the pressure minima identified in the NS and EW direction cross each other without directly overlapping. You can see an example of this situation in the figure below. The horizontal and vertical dashes shows the points identified as pressure minima in the NS direction and EW direction, respectively, and white circles show points where the two overlap. The method misses the low pressure center over central Europe.

![cyclones_example1](https://cloud.githubusercontent.com/assets/10116084/9577980/86432abc-4fe6-11e5-9e22-f5c56c5a2ec4.jpg)

The way I've handled this is to widen the bands of NS and EW low pressure points (see figure below). This gives you some extra cyclones but they are removed in the next step. This workaround is fast and easy but may not pinpoint all cyclone centers exactly. Anyone have an other idea? Do you think it's an acceptable solution?

![cyclones_example2](https://cloud.githubusercontent.com/assets/10116084/9577766/7ec7fd1e-4fe4-11e5-93d6-3374125c6f83.jpg)

**Comment by brasmus** [comment]
Not a bad idea. How slow is it to do both and then for duplicates keep the former? Also keep track of which is which (attribute?), so that we know that the latter is not as accurate.

**Comment by kajsamp** [comment]
I'll check how much extra time it takes and add an attribute keeping track of the accuracy of the cyclones.
