### ISSUE TITLE
I can't  INSTALL esd-master

### ISSUE THREAD

**Issue by napoliti** [metno/esd#112]
Hi, I am trying to install the esd-master but I got this message

s$ R CMD INSTALL esd-master
* installing to library ‘/home/nadia/R/x86_64-pc-linux-gnu-library/2.14’
ERROR: dependency ‘ncdf’ is not available for package ‘esd’
* removing ‘/home/nadia/R/x86_64-pc-linux-gnu-library/2.14/esd’

I installed the libnetcdf-dev from terminal sudo...etc, ok

I had also installed R and tried to continue:
R version 2.14.1 (2011-12-22)
Copyright (C) 2011 The R Foundation for Statistical Computing
ISBN 3-900051-07-0
Platform: x86_64-pc-linux-gnu (64-bit)

WITH > install.packages('ncdf4') AND > install.packages('zoo') -> ok installed
 and then checked the devtools package.
I got:
[1] "Need to install the devtools package"
Installing package(s) into ‘/home/nadia/R/x86_64-pc-linux-gnu-library/2.14’
(as ‘lib’ is unspecified)
Warning message:
In getDependencies(pkgs, dependencies, available, lib) :
  package ‘devtools’ is not available (for R version 2.14.1)

I am totally confuse.....and hope for some help!

CHeers

**Comment by abdelkaderm** [comment]
Hi there, 

You do not need the devtools. If you have already installed ncdf,ncdf4, and zoo dependencies, you can run directly

```r
 R CMD INSTALL esd-master
```
Bests,

**Comment by napoliti** [comment]
So I don 't take into consideration  the message below when I run  R CMD INSTALL esd-master?

* installing to library ‘/home/nadia/R/x86_64-pc-linux-gnu-library/2.14’
ERROR: dependency ‘ncdf’ is not available for package ‘esd’
* removing ‘/home/nadia/R/x86_64-pc-linux-gnu-library/2.14/esd’

**Comment by OskarMETNO** [comment]
It seems that you have installed the R package 'ncdf4', but not 'ncdf'.
Install 'ncdf' as well and then try again.
Cheers,
Oskar

**Comment by napoliti** [comment]
I got this message:
I can't install ncdf:
In getDependencies(pkgs, dependencies, available, lib) :
  package ‘ncdf’ is not available (for R version 2.14.1)
Do I have to change the R version? 

I tried to install on R shell but I got:

> install.packages("esd_1.0.tar.gz")
Installing package(s) into ‘/home/nadia/R/x86_64-pc-linux-gnu-library/2.14’
(as ‘lib’ is unspecified)
inferring 'repos = NULL' from the file name
Warning: invalid package ‘esd_1.0.tar.gz’
Error: ERROR: no packages specified

Any idea?

Thank you very much,

cheers,

Nadia

**Comment by abdelkaderm** [comment]
Hi,

It is recommended, if possible, to upgrade R to the latest version, but as far as I remember, ncdf should work with earlier versions of R, but not sure, try to upgrade your R system to the latest and let me know how are things going.

Bests,

**Comment by napoliti** [comment]
Hi,

I finally installed, the recent version of R (3.2.2) and all the necessary packages, but the latest package of ESD (esd_1.0.tar.gz) couldn’t be installed, so I tried the previous version (esd_0.9_2.tar.gz) and worked immediately!

I would like you to know in case there is something wrong with latest version.

cheers,

Nadia

**Comment by abdelkaderm** [comment]
Hi & Thanks,
It is good to know about it :-)
I will double check the latest package installation.
Bests,

**Comment by abdelkaderm** [comment]
What you can do is to download the package from https://github.com/metno/esd using the 'Download zip' bottom on the right menu bar to download the file locally, then install using R CMD command. This procedure should work as well.

**Comment by napoliti** [comment]
You have right!thanks
