### ISSUE TITLE
In esd can we draw contour plot of "stationdata" ?

### ISSUE THREAD

**Issue by monamidutta** [metno/esd#113]
In esd can we draw contour plot of "stationdata" ?
Suppose we have lon = 75.10 75.19 78.02 76.23 75.30 77.10 78.29 79.39 75.05 74.50 74.24 77.10 74.18 75.43 75.20 74.54
lat = 33.30 33.07 30.19 32.16 33.35 32.16 30.35 29.28 33.35 34.05 34.09 31.50 34.25 32.59 34.02 33.00
and values =   -3.2721040  -1.6490524   5.5556059  -1.5147047  -5.2594852  -7.4373113   2.8783942   7.0479222  -3.4037908  -6.6310745  -5.5571035  -0.1213006  -6.6647173   1.2005831 -10.4470082   2.1192882
Can i draw contour map of these? I tried to do, by converting the above to esd structure and zoo series, as we usually do for making station data but its giving error
> map(obj)
" Error in subset.zoo(x, it = it, is = is) : unused argument (is = is)"
I have also tried with package "fields", but its demanding of having lon (x) and lat(y) in ascending order. Which is bit difficult to arrange for me! can you suggest some thing in esd??

**Comment by brasmus** [comment]
See the demo script gridmap which uses the LatticeKrig package.
