### ISSUE TITLE
Incomplete Example in page 31. esd.pdf document. 

### ISSUE THREAD

**Issue by MeJitendra** [metno/esd#115]
![screenshot from 2015-09-28 12 01 05](https://cloud.githubusercontent.com/assets/11473497/10129173/e3666148-65d8-11e5-8cdb-15cdd5048240.png)

Sir, Please check the highlighted portion of the page 31 of esd.pdf document. The example seems incomplete.

Sincerely.

**Comment by abdelkaderm** [comment]
Fixed ! Thanks :)
