### ISSUE TITLE
Error: retrieve nc files using Windows, unknown file format

### ISSUE THREAD

**Issue by erlekr** [metno/esd#116]
Hi, 

I've been testing the esd package for some time now using a mac. I recently changed to windows 7 and I suddenly have a problem retrieving nc files. I've read through previous polls and can't find a solution. I have installed zoo and ncdf, and from what I read that should be OK. 

> ncep  <- retrieve("slp.mon.mean.nc")
Error in R_nc_open: NetCDF: Unknown file format
Error in open.ncdf(ncfile) : 
Error in open.ncdf trying to open file slp.mon.mean.nc

Any suggetions to what might cause this error? 

Best regards, 
Erle

**Comment by abdelkaderm** [comment]
Hi, 
Can you try the following and send me the output
```r
file.exists("slp.mon.mean.nc")
```
I am not sure whether the file path is broken or what ? Just to be sure that the file exists ?

**Comment by erlekr** [comment]
> setwd("C:/ncep")
> test <- retrieve("slp.mon.mean.nc")
Error in R_nc_open: NetCDF: Unknown file format
Error in open.ncdf(ncfile) : 
  Error in open.ncdf trying to open file slp.mon.mean.nc
> file.exists("slp.mon.mean.nc")
[1] TRUE

**Comment by abdelkaderm** [comment]
Oh yeah, I think I know why it is not working. Try replacing the dots '.' by '_' in the original file. I know that Windows struggle with dots in the file name.
Bests,

**Comment by erlekr** [comment]
Thank you, thats good to know! 

It doesn't seem to solve the problem unfortunately. I've tried the replacement as you suggest (slp_mon_mean.nc) and also slpmonmean.nc, and the same error occurs. I've also tested several other files without any luck.

**Comment by erlekr** [comment]
Hi,
So I've downloaded the ncd4 package (http://stackoverflow.com/questions/21637189/unable-to-open-netcdf-version-4-files-in-r), and it seems to work now if I use retrieve.ncfd4

> test <- retrieve.ncdf4("slp.mon.mean.nc")
Loading required package: ncdf4
[1] "Warning : Calendar attribute has not been found in the meta data and will be set automatically."

Best regards, 
Erle
