### ISSUE TITLE
retrieve - HDF error

### ISSUE THREAD

**Issue by brasmus** [metno/esd#122]
Error if I try to open the same file more than once: ```r2
Error in R_nc_open: HDF error
Error in open.ncdf(ncfile) : 
  Error in open.ncdf trying to open file air.mon.mean.nc
```

For instance 
```r2
Z.rcp45 <- DSensemble.annual(y,biascorrect=TRUE,
                             predictor="air.mon.mean.nc",
                             lon=c(-1,17),lat=c(57,62),
                              abscoords=TRUE)

Z.rcp85 <- DSensemble.annual(y,biascorrect=TRUE,
                             rcp="rcp85",predictor="air.mon.mean.nc",
                             lon=c(-1,17),lat=c(57,62),
                              abscoords=TRUE)
```

The problem is that 'ncdf' and 'ncdf4' get mixed up and that 'ncdf4' somehow is lingering in the code for DSensembles.

**Comment by brasmus** [comment]
The script works if you type `library(ncdf4)` and then repeat it.

**Comment by abdelkaderm** [comment]
Hi Rasmus, 

I fixed the problem, there was a missing ncdf.close in retrieve.default. 

My apologies.

Bests,
