### ISSUE TITLE
Problem in plotting CCA

### ISSUE THREAD

**Issue by MeJitendra** [metno/esd#127]
obs.jun<-subset(obs,it='jun')
pca.jun<-PCA(obs.jun) # pca of june month for station
rean.jun<-subset(rean,it='jun')
eof.jun<-EOF(rean.jun) # eof of jun month from eraint reanalysis data
cca.jun<-CCA(pca.jun,eof.jun)
plot(cca.jun)

Error in map.pca(Y, pattern = icca, xlim = xlim, ylim = ylim, type = type,  : 
  object 'lonR' not found

Please help.

**Comment by bczernecki** [comment]
There is something wrong with the plot.cca function while plotting CCA results. Here is the result from example given in help:

> plot(annual(NACD))
> map(NACD,FUN="sd")
> pca <- PCA(NACD)
> plot(pca)
> naslp <- slp.NCEP(lon=c(-30,40),lat=c(30,70),anomaly=TRUE)
> map(naslp)
> eof <- EOF(naslp,it=1)
> nacca <- CCA(pca,eof)
[1] "CCA.pca"
[1] "CCA.eof"
[1] "Barnett-Preisendorfer CCA"
> plot(nacca)
Error in map.pca(Y, pattern = icca, xlim = xlim, ylim = ylim, type = type,  : 
  object 'lonR' not found

It looks like 'map.cca' function calls for 'map' and there are no arguments given for lonR and latR

**Comment by abdelkaderm** [comment]
Hi there, 
I have fixed this recently. Please reinstall the package and try again.
Bests,

**Comment by brasmus** [comment]
:)
