### ISSUE TITLE
Description of DSensemble.precip generated graph. 

### ISSUE THREAD

**Issue by MeJitendra** [metno/esd#128]
Sir, I have two queries and one suggestion
Queries
1. Why the upper left (UL) insert in the below figure is gaussian with a extended tail, what are its x and y-axis values .
2.What is the y-axis values of the lower right (LR) insert ?

Suggestion
Please change the trend unit, C/decade to mm/decade in case of precipitation.
![screenshot from 2015-11-05 11 02 02](https://cloud.githubusercontent.com/assets/11473497/10963141/efca6d68-83c3-11e5-8022-228be8ea9631.png)

**Comment by abdelkaderm** [comment]
Hi Jitendra,

1. The inner in the top-left represents a quality check of the values falling outside the 90%. The curve shows a binomial distribution with a 10% probability of values to be exceeded.
2. The x-axis in the inner bottom right shows the trend values / decade
3. I will fix the unit in the caption, thanks :+1:

**Comment by MeJitendra** [comment]
Thank you sir. 
But, I want to know what is the Y-axis value of the inner bottom right? What are the gray coloured bars?

Some times, though the observation is entirely inside the simulated portion, still there is no 'black' circle in the top right inner (See the figure below), what is the possible reason? 
![dse simla mu](https://cloud.githubusercontent.com/assets/11473497/10964837/8601787a-83cf-11e5-9f9e-043a4de78021.png)

**Comment by abdelkaderm** [comment]
Hi,
The histograms of the inner-bottom-right shows the distribution of the trends computed for each downscaled GCM. The line represents a fitted distribution, and the black dot shows the historical trend position.

**Comment by MeJitendra** [comment]
Thank you sir. Now it is very clear.  :)

**Comment by brasmus** [comment]
We have now changed the look of the plot with quality target and map inserts.
