### ISSUE TITLE
Include additional colourscheme?

### ISSUE THREAD

**Issue by brasmus** [metno/esd#129]
One idea is to let esd read directly from the ASCII tables in:

http://geog.uoregon.edu/datagraphics/color_scales.htm

**Comment by kajsamp** [comment]
I added these colorschemes to the colscal function in esd. It probably would have been just as easy to have esd read them directly from the website but we can do that if we find any more color scales in the future. Anyway, we now have the following new colorschemes: 
GrMg (green to magenta)
BrBu (brown to blue)
BuDOr (blue to orange)
BuDRd (blue to red without any green)
BuGr (blue to green)
BuGy (blue to grey)
BuOr (blue to orange)
BuOrR (blue to orange to red)
Bu (blue)
Cat (categorical color scale, works for all viewers)

**Comment by brasmus** [comment]
Nice!

Rasmus
23. nov. 2015 15:49 skrev "kajsamp" <notifications@github.com>:
