### ISSUE TITLE
DS

### ISSUE THREAD

**Issue by abdelkaderm** [metno/esd#13]
You have recently added the argument `weighted` in DS, can you check the compatibility with DS.t2m.month.field() and other functions. I removed the `...` from the latter as I experienced a bug ...

DS.default <- function(y,X,mon=NULL,
                       method="lm",swsm="step",m=5,
                       rmtrend=TRUE,eofs=1:7,area.mean.expl=FALSE,
                       verbose=FALSE,**weighted=TRUE**,...)

**Comment by brasmus** [comment]
I inserted the agrument weighted=TRUE in all the other function calls, and now '...' will exclude this option. That makes the code more tidy. Thanks!
