### ISSUE TITLE
error while plotting a single station

### ISSUE THREAD

**Issue by monamidutta** [metno/esd#131]
Hello
In new esd package i am getting an error when i am trying to plot a single station after using subset command.
> stn1 <- subset(stationdata,is=1)
> plot(stn1)
Error in rgb(1 - ny, nx, ny, alpha) : color intensity nan, not in [0,1]

But the plot function is working well for group of stations.

Same problem for gridded data.

**Comment by brasmus** [comment]
I think this is already fixed. You need to reinstall esd.
