### ISSUE TITLE
Need some reference paper based on "DSensemble.precip"

### ISSUE THREAD

**Issue by MeJitendra** [metno/esd#132]
Dear Sir,
I am writing a paper based on "Dsensemble.precip". 
Please help me writing the literature review and methodology of the Dsensemble (Suggest me some published papers)

**Comment by brasmus** [comment]
The DSensemble function is very new, but we have some publications. Hansen, B., Isaksen, K., Benestad, R., Kohler, J., Pedersen, Å., Loe, L., Coulson, S., Larsen, J., Varpe, Ø., Warmer and wetter winters: characteristics and implications of an extreme weather event in the High Arctic, ERL 9 114021, doi:10.1088/1748-9326/9/11/114021
More papers are hopefully coming (submitted).
