### ISSUE TITLE
Building data sets manually

### ISSUE THREAD

**Issue by hohygen** [metno/esd#133]
The documentation on how to make monthly data for ESD if it's not availible online is good, but the documentation on how to create daily datasets is more challenging. Maybe a small function that reads a predefined datastructure from text files could be helpfull here, or at least a good description.

**Comment by abdelkaderm** [comment]
Hi,
I agree with you , 
I will double check the conversion function.
Thanks,

**Comment by abdelkaderm** [comment]
I added one example on how to built a station object manually in to the wiki page
https://github.com/metno/esd/wiki/2.-Data-handling#create-a-station-object-from-scratch-advanced-users
I hope this helps, if not just let me know!
Best,
