### ISSUE TITLE
testing predict.ds

### ISSUE THREAD

**Issue by erlekr** [metno/esd#134]
Hi,

I am testing the predict.ds function, but can't quite get it to work properly. Here's what I do: 

I have a station object, p.obs, of daily precipitation

p.obs <- annual(p.obs, FUN='wetfreq')

g.obs <- "slp.mon.mean.nc"
g.obs <- annual(retrieve(g.obs, lon=c(-15,15), lat=c(45,70)), FUN='mean')

eof.cal <- EOF(subset(g.obs, it=1948:2000))
eof.val <- EOF(subset(g.obs, it=2001:2015))

ds <- DS(p.obs, eof.cal)

(The DS works fine)

ds.predict <- predict.ds.eof(ds, newdata = eof.val, verbose=T)

And here's what I get: 

> ds.predict <- predict.ds.eof(ds, newdata = eof.val, verbose=T)
[1] "predict.ds.eof ds-field-annual-zoo"
[1] "eof-field-annual-zoo"
 [1] "X.1"  "X.2"  "X.3"  "X.4"  "X.5"  "X.6"  "X.7"  "X.8"  "X.9"  "X.10" "X.11" "X.12" "X.13" "X.14"
[1] "Use new data"

Call:
lm(formula = y ~ X.1 + X.2 + X.3 + X.5 + X.6 + X.7, data = caldat)

Residuals:
      Min        1Q    Median        3Q       Max 
-0.055561 -0.018572  0.000737  0.010598  0.061635 

Coefficients:
              Estimate Std. Error t value Pr(>|t|)    
(Intercept) -1.827e-18  3.891e-03   0.000  1.00000    
X.1         -3.132e-01  2.942e-02 -10.646 5.36e-14 ***
X.2          6.142e-02  2.919e-02   2.104  0.04086 *  
X.3         -1.226e-01  2.857e-02  -4.290 9.09e-05 ***
X.5         -8.206e-02  2.836e-02  -2.893  0.00581 ** 
X.6          8.229e-02  3.160e-02   2.604  0.01236 *  
X.7          6.029e-02  2.849e-02   2.116  0.03978 *  
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 0.02833 on 46 degrees of freedom
Multiple R-squared:  0.7829,	Adjusted R-squared:  0.7546 
F-statistic: 27.65 on 6 and 46 DF,  p-value: 1.04e-13

Error in UseMethod("predict") : 
  no applicable method for 'predict' applied to an object of class "c('double', 'numeric')"
In addition: Warning message:
In predict.ds.eof(ds, newdata = eof.val, verbose = T) :
  newdata and X have different number of EOFs

As a result the ds.predict object is not returned. Am I doing it right? Or do you have any suggestions to what may cause the error? 

Best, 
Erle

**Comment by kajsamp** [comment]
Hi Erle,

There was a bug in ds.predict but I think I''ve fixed it. Update esd and try again. Let me know if it works or not. 

Thanks,
Kajsa

**Comment by erlekr** [comment]
Thank you very much! Works now :)
