### ISSUE TITLE
Grid point correlation (corfield)

### ISSUE THREAD

**Issue by martaddi** [metno/esd#136]
Hi,
I am quite new to R.I want get the correlation map between a reanalysis SST data and a PC time series data.Below is the command I used
Open the data
Nc<-open.ncdf("SST.nc")
St<-read.table("pc1.txt",header=T,sep=",")
Then I used the function in esd 
CD<-corfield.station(Nc,St)
But got an error message
Error: inherits(X,"station") is not TRUE

Please what should I do.
Thank you.

**Comment by brasmus** [comment]
Neither Nc nor St are esd-objects. Please read our documentation and see our examples.

**Comment by martaddi** [comment]
Thank you. So how can I use esd to analysis my own data without using the data object in  esd package?Example read my data,set my dimensions and use esd package to analysis.
