### ISSUE TITLE
DSensemble problem, traced to svd: "Error in La.svd"

### ISSUE THREAD

**Issue by kajsamp** [metno/esd#137]
Hi Rasmus and Abdelkader, 

I'm using DSensemble and run in to the following message: 
"Error in La.svd(x, nu, nv) : error code 1 from Lapack routine 'dgesdd'". 

The error comes from the base function La.svd when doing the EOF analysis of the combined predictor and GCM. It only happens for some ensemble members and I can't see anything obviously wrong with those GCMs. I've googled the issue and it seems like svd sometimes fails when it shouldn't. According to this discussion, different matrices cause this error on different platforms, so it can be difficult to reproduce: https://bugs.r-project.org/bugzilla/show_bug.cgi?id=14950

Any ideas how to deal with this? For now, I'll just exclude the GCMs that don't work but I would like to find a better solution. 

Kajsa

**Comment by brasmus** [comment]
Yes, it's a problem. I suspect that the matrix is close to being singular. you can try with a different domain (e.g. increase the lon/lat range).

**Comment by kajsamp** [comment]
I found two interesting work-arounds when svd(x) doesn't work
1) try svd(t(x)) instead. It is rare that both fail.
2) round the matrix, e.g. svd(round(x,digits=10))
Not sure why this work but it does.

**Comment by brasmus** [comment]
I guess we should try to include a test for this ('try'?)

**Comment by kajsamp** [comment]
I have added a few lines in EOF to try svd(t(x)) when svd(x) fails.
