### ISSUE TITLE
How to open my own data and analysis

### ISSUE THREAD

**Issue by martaddi** [metno/esd#139]
I am new and want to know how to use esd to analysis my own data without using the data object in esd package?Example read my data,set my dimensions and use esd package to analysis.

**Comment by OskarMETNO** [comment]
Hi!
You first need to get your data into R. How to do that depends on the format of your data.
If you are completely new to R you can find a lot of information (e.g. on Stackoverflow). Usually a google search with some more information helps.

In short:
If you have NetCDF data you can use the ncdf or ncdf4 packages in R.
If you have the data as a text file you can use the read.table() function.

Hope this helps!

**Comment by brasmus** [comment]
esd is written to read in new data, and this is described on the wiki-page here on GitHub and the documentation.

**Comment by martaddi** [comment]
Thank you
 


    On Thursday, November 26, 2015 10:30 AM, Rasmus E. Benestad <notifications@github.com> wrote:
 

 esd is written to read in new data, and this is described on the wiki-page here on GitHub and the documentation.—
