### ISSUE TITLE
plot.dsensemble & plot.diagnose.dsensemble

### ISSUE THREAD

**Issue by brasmus** [metno/esd#141]
Needs to being tidied up. Lines in `plot.diagnose.dsensemble` are hard-coded to the default fig size. 

![screenshot from 2015-12-01 14 29 32](https://cloud.githubusercontent.com/assets/7392034/11501928/fe22c116-9837-11e5-9c4a-eb68e159ee04.png)

**Comment by kajsamp** [comment]
I have cleaned up plot.dsensemble and plot.dsensemble.diagnose. The map can be turned off with map.show=FALSE. The default plot shows the station as points on a map (map.type="points") but you can also show the region of interest as a box (map.type="rectangle"), like in the example below where I have downscaled storm statistics for the Barents region.
[dse.barents.deepcyclones.rcp85.pdf](https://github.com/metno/esd/files/56958/dse.barents.deepcyclones.rcp85.pdf)

**Comment by brasmus** [comment]
Looks good! I think we can include plots for RCP2.6, 4.5 for both M03,
M06(?) and M16 in the atlas:)

R
