### ISSUE TITLE
Install errors in windows 7 64bit system?

### ISSUE THREAD

**Issue by dave2004NMC** [metno/esd#144]
Hi, I want to install esd package in windows 7 64bit system with the fellowing commands:
library('devtools')
install_github('metno/esd')

But failed and get the errors:

> library('devtools')
> install_github('metno/esd')
Downloading GitHub repo metno/esd@master
Installing esd
"C:/PROGRA~1/R/R-32~1.3/bin/x64/R" --no-site-file --no-environ --no-save  \
  --no-restore CMD INSTALL  \
  "C:/Users/daikan/AppData/Local/Temp/RtmpqQYMEq/devtoolsa1b42a387ef3/metno-esd-
8371d28"  \
  --library="C:/Program Files/R/R-3.2.3/library" --install-tests

* installing *source* package 'esd' ...
** R
Error in parse(outFile) : 174
ERROR: unable to collate and parse R files for package 'esd'
* removing 'C:/Program Files/R/R-3.2.3/library/esd'
: Command failed (1)
>

So how to solve this? thanks!

**Comment by brasmus** [comment]
Hi, Try to download the zip-file from this site, save and install locally (try install_local('esd-master')). There are also some instructions on the wiki pages on this site. Any success?
