### ISSUE TITLE
Monthly/seasonal precipitation 

### ISSUE THREAD

**Issue by erlekr** [metno/esd#148]
Hi, 
I'm interested in the development of monthly (or seasonal) preciptiation projected by an ensemble of GCMs. Do you have any suggestions on how to downscale an ensemble of models on a monthly timestep? The DSensemble function automatically downscales on an annual time resolution, and the DS function only takes one GCM at a time as far as I can see. 

Thank you and all the best, 
Erle Kristvik

**Comment by abdelkaderm** [comment]
Hi, Erle

Please find attached a script that I have written recently for downscaling monthly temperature that you can adapt to precipitation. However, we do not recommend this way of downscaling as the link with the large scale information becomes very weak. For that reason, we are developing a new strategy based on downscaling seasonal or annual precipitation characteristics (such as wet-day mean and frequency) then disaggregating into monthly or daily time steps. But we are not finished yet. Any way please find the script here 
[DSensemble.month.txt](https://github.com/metno/esd/files/97355/DSensemble.month.txt)

Bests, 

Abdelkader
