### ISSUE TITLE
as.4seasons gives NAs

### ISSUE THREAD

**Issue by anitavd** [metno/esd#149]
I have a dse.ensemble / zoo object (which plots well), that I want to split into seasons
with as.4seasons. The command runs, but it produces a series of only NAs.

**Comment by anitavd** [comment]
Now I get the following error when I try to plot the dseensemble/season object:
Error in inherits(y, "try-error") : object 'y' not found

**Comment by abdelkaderm** [comment]
Resolved :+1:
