### ISSUE TITLE
missing attribute in CMIP-files

### ISSUE THREAD

**Issue by anitavd** [metno/esd#151]
The model_id attribute seems to be missing from the following file:
/vol/klimadata/work/abdelkaderm/CMIP5.monthly//rcp45/pr_Amon_ens_rcp45_034.nc

**Comment by brasmus** [comment]
It's missing in the file downloaded from ClimateExplorer, but according to the history attribute it should be 'EC-EARTH_rcp45_r3i1p1'. You can set this mannually. Missing attribute is not critical.
