### ISSUE TITLE
devtools not available for Fire Safety (R version 3.2.2)

### ISSUE THREAD

**Issue by Marston** [metno/esd#152]
Hi!

I'm trying to use the ESD package via pyr2 on a Linux cluster and on my Mac El Capitan.
On both machines I have R Fire Safety and when I try to install devtools, it says that it is not available for this version of R. Since I am using pyr2 to call R Anaconda installs the latest version of R.

Is there a work around?

**Comment by abdelkaderm** [comment]
Hi there, 

Yes, you could try several options detailed in the wiki page on 'How to install' (https://github.com/metno/esd/wiki/0.-How-to-install%3F) . Specifically, try to install it directly from a Shell/Terminal.

Bests,

**Comment by Marston** [comment]
Hi,

I've downloaded devtools and installed via the terminal command but ncdf will not install in my Anaconda environment. The package simply does not exit anymore and have been replaced with netcdf4. Which makes me wonder why is ESD still using ncdf. 

When I try and install ncdf directly in R from terminal I get the following message:

Marstons-MacBook-Pro:Downloads marston$ R CMD INSTALL ncdf_1.6.9.tar.gz
* installing to library ‘/Users/marston/Library/R/3.2/library’
* installing *source* package ‘ncdf’ ...
** package ‘ncdf’ successfully unpacked and MD5 sums checked
checking for nc-config... /Users/marston/anaconda/bin/nc-config
configure: creating ./config.status
config.status: creating src/Makevars
** libs
clang -I/Users/marston/anaconda/lib/R/include -DNDEBUG -I/Users/marston/anaconda/include -I/Users/marston/anaconda/include    -fPIC  -I/Users/marston/anaconda/include  -c ncdf.c -o ncdf.o
clang -I/Users/marston/anaconda/lib/R/include -DNDEBUG -I/Users/marston/anaconda/include -I/Users/marston/anaconda/include    -fPIC  -I/Users/marston/anaconda/include  -c ncdf2.c -o ncdf2.o
clang -I/Users/marston/anaconda/lib/R/include -DNDEBUG -I/Users/marston/anaconda/include -I/Users/marston/anaconda/include    -fPIC  -I/Users/marston/anaconda/include  -c ncdf3.c -o ncdf3.o
clang -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Users/marston/anaconda/lib/R/lib -L/Users/marston/anaconda/lib -lgfortran -o ncdf.so ncdf.o ncdf2.o ncdf3.o -L/Users/marston/anaconda/lib -lnetcdf -L/Users/marston/anaconda/lib/R/lib -lR -Wl,-framework -Wl,CoreFoundation
installing to /Users/marston/Library/R/3.2/library/ncdf/libs
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
Error in dyn.load(file, DLLpath = DLLpath, ...) :
  unable to load shared object '/Users/marston/Library/R/3.2/library/ncdf/libs/ncdf.so':
  dlopen(/Users/marston/Library/R/3.2/library/ncdf/libs/ncdf.so, 6): Library not loaded: libnetcdf.7.dylib
  Referenced from: /Users/marston/Library/R/3.2/library/ncdf/libs/ncdf.so
  Reason: image not found
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/Users/marston/Library/R/3.2/library/ncdf’

And since ncdf will not install, ESD will not either, sigh!

**Comment by abdelkaderm** [comment]
We moved to ncdf4 last week. Please check the wiki news. I did not update the wiki 'how to install', will do it as soon as possible. To sum up, you can install esd now as it is using ncdf4, :+1: 
Bests,

**Comment by Marston** [comment]
Hi,

Sorry for the delay in responding. I've now managed to install ESD in R 3.2.2.
Thanks for your help.
/M
