### ISSUE TITLE
cyclic namespace dependency

### ISSUE THREAD

**Issue by kajsamp** [metno/esd#154]
I just updated esd got this error when I tried to install:
```
* installing to library ‘/home/kajsamp/R_LIBS’
* installing *source* package ‘esd’ ...
** R
** data
** demo
** preparing package for lazy loading
Error in loadNamespace(package, c(which.lib.loc, lib.loc)) : 
  cyclic namespace dependency detected when loading ‘esd’, already loading ‘esd’
Error : package or namespace load failed for ‘esd’
Error : unable to load R code in package ‘esd’
ERROR: lazy loading failed for package ‘esd’
* removing ‘/home/kajsamp/R_LIBS/esd’
* restoring previous ‘/home/kajsamp/R_LIBS/esd’
```

**Comment by kajsamp** [comment]
Hmm, it worked perfectly fine to install with devtools.

**Comment by abdelkaderm** [comment]
Try now, I did a small fix in NAMESPACE, but do not think this was a problem, works fine with R CMD command as well.

**Comment by kajsamp** [comment]
I still get the same error

**Comment by abdelkaderm** [comment]
I did a pull and reinstall it again, and everything worked fine, you may need to close your R session and restart it again, I think that you have an internal problem.

**Comment by abdelkaderm** [comment]
Hi Kajsa,
I tried installing esd on my personal mac and seems to work only using devtools::install_github or devtools::github_local. I got an error when installing using R CMD INSTALL command. 

My session info is the following

```r
> sessionInfo()
R version 3.0.3 (2014-03-06)
Platform: x86_64-apple-darwin10.8.0 (64-bit)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] esd_1.0    zoo_1.7-12 ncdf4_1.13

loaded via a namespace (and not attached):
[1] grid_3.0.3      lattice_0.20-27
```

**Comment by kajsamp** [comment]
Problem solved. Turns out there was an R script in the esd/R/ folder on my computer that wasn't supposed to be there. Now everything works fine.
