### ISSUE TITLE
colbar option in corfield in not working 

### ISSUE THREAD

**Issue by monamidutta** [metno/esd#157]
I wanna fixed the legend of corfield map from -1 to +1 so i have wrote
corfield(stnwin1,win,colbar=list(breaks=seq(-1,1,by=0.2)))
but its generating map with following legend
[Rplot.pdf](https://github.com/metno/esd/files/113624/Rplot.pdf)

need help...

**Comment by brasmus** [comment]
It works, but you need to include it in a list. 'colbar=list(breaks=seq(-1,1,by=0.2))'
