### ISSUE TITLE
How to draw map for different EOFs seperately???

### ISSUE THREAD

**Issue by javakh** [metno/esd#158]
After making in eof object e.g.
e=EOF(x)
we get 20 eofs (if we dont specify 'n')
But when when we use **map(e)** we get only one map.
I want to know how can we make 20 separate maps for 20 eofs???

Thanks.

**Comment by abdelkaderm** [comment]
Use `pattern` argument to specify which eof to map, try
```r
map(eof , pattern = 1) ## EOF1 
map(eof , pattern = 2) ## EOF2
map(eof , pattern = 3)  ## EOF3
```
and so on ....
