### ISSUE TITLE
error message: example from pdf page 44

### ISSUE THREAD

**Issue by honglioslo** [metno/esd#160]
How to solve the problem in predict and project? Thanks
...
> library(esd)
Error in library(esd) : there is no package called ‘esd’
> library(devtools)
> install_github("metno/esd")
Downloading GitHub repo metno/esd@master
from URL https://api.github.com/repos/metno/esd/zipball/master
Installing esd
'/usr/lib/R/bin/R' --no-site-file --no-environ --no-save --no-restore CMD  \
  INSTALL '/tmp/RtmpzoQ5br/devtools2d196fbd630a/metno-esd-451611b'  \
  --library='/home/hongl/R/x86_64-pc-linux-gnu-library/3.2' --install-tests 

* installing *source* package ‘esd’ ...
** R
** data
** demo
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
* DONE (esd)
> library(esd)
Loading required package: ncdf4
Loading required package: zoo

Attaching package: ‘zoo’

The following objects are masked from ‘package:base’:

    as.Date, as.Date.numeric

Attaching package: ‘esd’

The following object is masked from ‘package:base’:

    subset.matrix

> data(Oslo)
> # Get ERA40 2m air temperature
> t2m <- t2m.ERA40(lon=c(0,20),lat=c(50,70))
> # Get NorESM.M 2m air temperature
> T2m <- t2m.NorESM.M(lon=c(lon=c(0,20),lat=c(50,70)))
> # Combine the two fields
> comb <- combine(t2m,T2m)
[1] "Warning - different units: deg C degC"
> # Compute the common eof t2m
> ceof <- EOF(comb)
> # Do the downscaling of y based on X
> ds <- DS(Oslo,ceof)
> # Subset the calibration
> z.calibration <- predict(ds,newdata=EOF(t2m))
Warning message:
In predict.ds.eof(x, newdata = newdata, addnoise = addnoise, n = n,  :
  newdata and X have different number of EOFs
> z.projection <- project.ds(ds)
Error in eval(expr, envir, enclos) : object 'X.2' not found
In addition: Warning message:
In predict.ds.eof(x = x, newdata = newdata, addnoise = FALSE, n = 100) :
  newdata and X have different number of EOFs

...

**Comment by brasmus** [comment]
The problem is now solved, although there is still a warning message
