### ISSUE TITLE
retrieve probelm

### ISSUE THREAD

**Issue by honglioslo** [metno/esd#161]
I used retrieve to get data from a netcdf file. It is post-processing from wrf simulation. How can use this dataset in ds? Thanks

> ncFileName
[1] "/home/hongl/Hong/DownScale/Data/tas_daily_regionalsubset.nc"
> X <- retrieve(ncFileName,verbose=TRUE)
[1] "retrieve.default"
[1] "Irregular grid field found"
Error in retrieve.rcm(ncfile, path = path, param = param, verbose = verbose,  : 
  unused argument (path = path)
> X <- retrieve.ncdf(ncFileName, verbose=TRUE)
[1] "retrieve.ncdf"
Error in retrieve.ncdf(ncFileName, verbose = TRUE) : 
  promise already under evaluation: recursive default argument reference or earlier problems?

**Comment by abdelkaderm** [comment]
Hi Li, 

I have done a quick fix in `retrieve.rcm`, please reinstall and try again. There was a problem in defining the file path name.

Bests,

**Comment by abdelkaderm** [comment]
try now ! Sorry, Li (reinstall the package first)
