### ISSUE TITLE
retrieve probelm

### ISSUE THREAD

**Issue by honglioslo** [metno/esd#162]
Hei Did you try it? There are new errors. Besides, lon and lat are an array, so dim function does not work.

> remove.packages("esd")
Removing package from ‘/home/hongl/R/x86_64-pc-linux-gnu-library/3.2’
(as ‘lib’ is unspecified)
> library(devtools)
> install_github("metno/esd")
Downloading GitHub repo metno/esd@master
from URL https://api.github.com/repos/metno/esd/zipball/master
Installing esd
'/usr/lib/R/bin/R' --no-site-file --no-environ --no-save --no-restore CMD  \
  INSTALL '/tmp/RtmpiQup7U/devtools76445e7adefd/metno-esd-f5121e5'  \
  --library='/home/hongl/R/x86_64-pc-linux-gnu-library/3.2' --install-tests 

* installing *source* package ‘esd’ ...
** R
** data
** demo
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
* DONE (esd)
Reloading installed esd

Attaching package: ‘esd’

The following object is masked from ‘package:base’:

    subset.matrix

> library(esd)
> X <- retrieve.ncdf(ncFileName, verbose=TRUE)
[1] "retrieve.ncdf"
Error in retrieve.ncdf(ncFileName, verbose = TRUE) : 
  promise already under evaluation: recursive default argument reference or earlier problems?
> X <- retrieve(ncFileName,verbose=TRUE)
[1] "retrieve.default"
[1] "Irregular grid field found"
[1] "retrieve.rcm tas_daily_regionalsubset.nc"
Error in R_nc4_open: No such file or directory
Error in nc_open(ncfile) : 
  Error in nc_open trying to open file tas_daily_regionalsubset.nc
> ncFileName
[1] "/home/hongl/Hong/DownScale/Data/tas_daily_regionalsubset.nc"

**Comment by abdelkaderm** [comment]
try
```r
X <- retrieve.rcm(ncFileName, verbose=TRUE)
```

**Comment by honglioslo** [comment]
the test data is /vol/fou/klima/hongl/esd_prob/tas_daily_regionalsubset.nc

**Comment by abdelkaderm** [comment]
Hi Li, 
I made for fixes in `retrieve.rcm()`, should work now !
Hilsen,
```r
rcm <- retrieve.rcm("tas_daily_regionalsubset.nc",param='tas')
> map(rcm,FUN='mean')
```

**Comment by honglioslo** [comment]
Yes, it works. Thank you. But if add verbose= TRUE. There are some message, maybe not nice.
Thanks

> rcm <- retrieve.rcm(ncFileName,param='tas', verbose = TRUE)
[1] "retrieve.rcm /home/hongl/Hong/DownScale/Data/tas_daily_regionalsubset.nc"
[1] "units"       "coordinates" "FieldType"   "MemoryOrder" "description"
[6] "stagger"    
Error in paste("unit: ", vunit, "; time unit: ", tunit, "; time origin: ",  : 
  object 'torg' not found

**Comment by abdelkaderm** [comment]
Fixed now !
