### ISSUE TITLE
error in retrieve some .nc files

### ISSUE THREAD

**Issue by monamidutta** [metno/esd#163]
Hye,
 i am getting an error while retrieving ncfile:
retrieve("F:/Monami_Dutta/DATA/gcm_concatenate_files_AR5/RCP85/from rasmus/tas_Amon_ens_rcp85_000.nc",lon=c(60,90),lat=c(20,40)) ### KNMI data

Error in R_nc_open: NetCDF: Unknown file format
Error in open.ncdf(file.path(path, ncfile)) : 
  Error in open.ncdf trying to open file 

While with the same function is working for other ncfiles (e.g gcms, eraint)
 retrieve("F:/Monami_Dutta/DATA/gcm_concatenate_files_AR5/RCP85/full_tas_Amon_BNU-ESM.nc",lon=c(60,90),lat=c(20,40))# raw GCM output
or 
t2m <- retrieve("2 m air temp.nc",lon=c(60,90),lat=c(20,40),it=c(1979:2003)) ### ERAINT

Why so????????
Note : i have applied the possible ways that is suggested in Github before relating this issue

**Comment by abdelkaderm** [comment]
Hi Monami, 

Can you send me a link to the file "F:/Monami_Dutta/DATA/gcm_concatenate_files_AR5/RCP85/from rasmus/tas_Amon_ens_rcp85_000.nc", you can share it with me using Google drive or Dropbox, so I can have a deep look into the problem ...

Thanks

**Comment by abdelkaderm** [comment]
Thanks for sharing the file, 
I did not get any problem using both ncdf or ncdf4 library to read the file. The file looks ok!
You may need to reinstall the package! but wait until I include the changes into the 'master-ncdf' branch.

Bests,

**Comment by monamidutta** [comment]
i have remove the package **ncdf** (remove.packages(ncdf)) from R once, after that **esd** is not working but i have **ncdf4**. i assumed that **esd** is based on **ncdf**. But in latest version of R **ncdf** package has been removed, so now i am unable to re install ncdf and cannot work with **esd** in new version of R. In addition i have also tried to install **esd** in R lower version (3.0.3, because in that **ncdf** is available) but there **devtools** is not available, which is required for installing **esd**.
Can't figure it.

**Comment by monamidutta** [comment]
i just wanted to comment that my above problems is doing well in new esd package. Thank you

**Comment by abdelkaderm** [comment]
Hi Monami, 
So were you able to do the installation or not? I am a bit confused here !
Bests,

**Comment by monamidutta** [comment]
Yes i was able to install the esd and working well but still getting error in DSensemble.
ds.85 <- DSensemble(st1,plot=TRUE,path="F:/Monami_Dutta/DATA/gcm_concatenate_files_AR5/", rcp="RCP26",biascorrect=FALSE, predictor="F:/Monami_Dutta/DATA/ERAINT/final/New Folder/2 m air temp.nc", non.stationarity.check=FALSE,lon=c(60,100),lat=c(5,45), select=NULL, FUN="mean", pattern="tas_Amon",verbose=TRUE)
Error in retrieve.default(ncfile = predictor, lon = lon, lat = lat, type = type,  : 
  could not find function "open.ncdf"

and also getting error while plotting the daily station data
**plot(dailystmn)**
Error in if (varnm == "t2m") varnm <- "T[2*m]" : 
  missing value where TRUE/FALSE needed

**Comment by abdelkaderm** [comment]
From which branch have you installed the package 'master' or 'master-ncdf' ?

**Comment by monamidutta** [comment]
In R
install_github("metno/esd")

**Comment by abdelkaderm** [comment]
then, you have installed the 'master' branch with ncdf4 dependency. I did a quick fix for the first issue here, please reinstall the package and try again. Hopefully, it will work :+1: 
For you second question, it seems like variable name is NA, please apply `str` and send me the output, 
`str(dailystmn)`
thanks

**Comment by monamidutta** [comment]
![image](https://cloud.githubusercontent.com/assets/11063879/13277105/375734a2-daec-11e5-9b8f-046fe74ea63e.png)

**Comment by monamidutta** [comment]
![image](https://cloud.githubusercontent.com/assets/11063879/13277112/4da5a7fc-daec-11e5-9da3-a6bcb5e81b2d.png)
 yes you are right the variable name was "NA". Now i have changed it to "t2m". The DSensemble is also working. :)
Thank you

**Comment by abdelkaderm** [comment]
Perfect, the figure looks great :+1: , well done !

**Comment by monamidutta** [comment]
i am trying to downscale station location temp data using mean sea level pressure (GCM and ERAINT) in similar fashion that i have done before for temperature (GCM and ERAINT)  and running the same code as before.
but now i am getting an error for DSensemble. Please find the attachment
![image](https://cloud.githubusercontent.com/assets/11063879/13318361/572a01fc-dbe0-11e5-8b6b-bf5f1df68470.png)

**Comment by abdelkaderm** [comment]
Try to read the file using `retrieve' to read the data in psl_Amon_ens_rcp26_002.nc first before calling `DSensemble'.

**Comment by monamidutta** [comment]
i have done it and its working

**Comment by abdelkaderm** [comment]
Hi again, 
I have done some more fixes to avoid conflicts between Windows and Linux users. Please reinstall and try again.
Best,

**Comment by monamidutta** [comment]
i have reinstalled it using install_github("metno_esd"). But same error is persisting.

**Comment by abdelkaderm** [comment]
the command install_github("metno_esd") is not correct, do you mean install_github("metno/esd") ?

**Comment by monamidutta** [comment]
yes.i apologize for the mistake, i wrote incorrectly in here. It is
install_github("metno/esd")

Monami Dutta
Ph.D student, Department of Agricultural Meteorology
and Physics,B.C.K.V, Mohanpur, Nadia
West Bengal,India

**Comment by abdelkaderm** [comment]
The problem here is fixed !
