### ISSUE TITLE
as.station problem

### ISSUE THREAD

**Issue by honglioslo** [metno/esd#167]
I have a filed object read from ncfile, then I use as.station to convert to station object. But the locations are not correct. I put the save data at /home/hongl/Dropbox/INDICE/esd_prob/temp.RData
script is : StasAPHRODITE <- as.station.field(APHRODITE);
or StasAPHRODITE <- as.station(APHRODITE);

![sta](https://cloud.githubusercontent.com/assets/16225129/13280294/67be4c2a-dadd-11e5-80b1-342a1f6a15fd.png)
![field](https://cloud.githubusercontent.com/assets/16225129/13280295/688fd07e-dadd-11e5-8564-8df14c09a1ce.png)

1000 takk

**Comment by abdelkaderm** [comment]
Hi there, 
I think this is happening because your APHRODITE data is regular, so you may need to read it using `retrieve.rcm()` function which will read the gridded data as stations, directly :+1:

**Comment by honglioslo** [comment]
i did try, but it does not work. The file is APHRO (interpolated station precipitation) in netcdf format.
> APHRODITE2 <- retrieve.rcm(APHRODITEfile, param='precip', verbose = TRUE);
[1] "retrieve.rcm /disk1/Work/DownScale/Data/Jhelum_APHRO_MA_025deg_V1101.All.nc"
[1] "long_name"         "units"             "_FillValue"       
[4] "missing_value"     "level_description"
[1] "unit: mm/day; time unit: days; time origin: 1951-01-01"
Error in if (substr(varid, 1, 1) == "/") stop(paste("Error, I was given a name that starts with a slash; fully qualified names NEVER start with a slash (this is required for backwards compatability).  Leave off the leading slash!")) : 
  argument is of length zero

**Comment by abdelkaderm** [comment]
One question, why would you like to convert the field into stations ?

**Comment by abdelkaderm** [comment]
your varid in the netcdf file is different from 'precip', please check it up and try again, otherwise, set param='auto', it may work but not sure.

**Comment by abdelkaderm** [comment]
You can try the handy function `summary.ncdf4() function to do a quick check on the file content, sth like
```r
summary.ncdf4(APHRODITEfile) 
```

**Comment by abdelkaderm** [comment]
I have also did q quick fix in as.station.field function, now the following command 
`StasAPHRODITE <- as.station.field(APHRODITE)`
should work !
