### ISSUE TITLE
mapping the sum or multiplication of two GCM

### ISSUE THREAD

**Issue by Sanjana-Priyadarshini** [metno/esd#168]
Hii! there
I am woking on the GCM  and found problem in mapping. Please see the following error I got while mapping multiplication of two gcms
> x = retrieve('tas1.nc', lat=c(7,40), lon=c(70,97), it=c(1981,2005))
> y = retrieve('tas2.nc', lat=c(7,40), lon=c(70,97), it=c(1981,2005))
> map(x)
> map(y)
> z = x+y
> map(z)

Error in subset.zoo(x, it=it, is=is): unused argument is=is

Help please.!!

**Comment by abdelkaderm** [comment]
Hi there, 
`retrieve` function returns a zoo object with additional attributes and classes. When you do mathematical operations on 'esd objects', most of the attributes are lost, so you have to take car of this seperately. You can try the following:
```r
z = x+y
z <- attrcp(x,z) ## copy the attributes from x or y to z
class(z) <- class(x) ## copy the class from x or y to z
map(z)
```
