### ISSUE TITLE
DS does not work anymore

### ISSUE THREAD

**Issue by honglioslo** [metno/esd#171]
hei, my old code, which was sucessful, does not work anymore. The error is the DS function.
I have put the code TasEsd_ChenabOneWrf.R and used data in /home/hongl/Dropbox/INDICE/esd_prob
------------------------------------------------------------------------------------------------------
Coefficients:
              Estimate Std. Error t value Pr(>|t|)    
(Intercept) -4.356e-16  8.856e-02   0.000   1.0000    
X.1          7.900e+02  1.323e+01  59.732  < 2e-16 ***
X.2          1.970e+02  1.372e+01  14.358  < 2e-16 ***
X.3          2.640e+01  1.186e+01   2.227   0.0263 *  
X.4          2.020e+01  1.322e+01   1.528   0.1269    
X.5         -1.084e+02  1.456e+01  -7.444 2.78e-13 ***
X.6          2.522e+01  1.345e+01   1.876   0.0611 .  
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 2.393 on 723 degrees of freedom
Multiple R-squared:  0.8519,	Adjusted R-squared:  0.8507 
F-statistic: 693.3 on 6 and 723 DF,  p-value: < 2.2e-16

[1] "pattern dimension"
[1] 30 30 20
 num [1:30, 1:30, 1:20] 0.0332 0.033 0.0329 0.0323 0.0319 ...
[1] "predict"
Error in attr(y, nattr[i]) <- attr(x, nattr[i]) : 
  length of 'dimnames' [2] not equal to array extent

**Comment by brasmus** [comment]
This should now be fixed.
