### ISSUE TITLE
WG

### ISSUE THREAD

**Issue by erlekr** [metno/esd#174]
Hi,
Would it be possible to see an example on how to use the precipitation weather generator with downscaled results? Do you have any suggestions on papers to read? 

Thank you and all the best, 
Erle Kristvik

**Comment by brasmus** [comment]
The weather generators in esd are still in an early stage, but we are planning to develop them in the near future. There are many ways to design weather generators, depending on which aspects are more important. Check out WG.fw.day.precip (various forms starting with WG).

The idea with the WGs is that you prescribe the parameters of some PDF (e.g. gaussian for temperature gamma/exponential for precip), and use downscaling to predict how these parameters (e.g. mean or wet-day mean) change under a climate change. For precipitation we need to also predict the frequency of rainy days in addition to the amount. We also will try to include information about the statistics of dry and wet spells. 

More on EWGs:
[Mezghani & Hingray](https://www.researchgate.net/publication/223687291_A_combined_downscaling-disaggregation_weather_generator_for_stochastic_generation_of_multisite_hourly_weather_variables_over_complex_terrain_Development_and_multi-scale_validation_for_the_Upper_Rhone_)
http://www.ipcc-data.org/guidelines/pages/weather_generators.html
http://unfccc.int/adaptation/nairobi_work_programme/knowledge_resources_and_publications/items/5510.php
http://ukclimateprojections.metoffice.gov.uk/22540

and references therein.

**Comment by erlekr** [comment]
Thank you!
