### ISSUE TITLE
CCA plots

### ISSUE THREAD

**Issue by monamidutta** [metno/esd#184]
what is x-axis in the CCA plot (two maps) of reanalysis and GCM in the following plot?
![image](https://cloud.githubusercontent.com/assets/11063879/14626297/cc902bd2-0607-11e6-8a32-c05d02d1e4ce.png)

**Comment by monamidutta** [comment]
Yes, color bar of two maps

**Comment by abdelkaderm** [comment]
It corresponds to the EOF pattern, but the magnitude of the pattern is meaningless, the only thing that does count here, is the spatial pattern, i.e. how it is spatially distributed :+1:
