### ISSUE TITLE
Make projections with several variables?

### ISSUE THREAD

**Issue by erlekr** [metno/esd#185]
Hi!

I want to make projections by downscaling GCMs. From example 4.4 I understand that one can use combine(reanalysis, gcm) such that the model is calibrated with the reanalysis data and projections are made with the gcm data. This works fine, but what do I do if I want several explanotary variables? In example 5.1 list(t2m, slp) is used. Both examples works fine with my data, but I can't find a way to include projection data when using list(). I have tried: 

c1 <- EOF(combine(gobs.t2m, gcm.t2m))
c2 <- EOF(combine(gobs.precip, gcm.precip))
z <- DS(p.obs, list(t2m = c1, precip = c2))

which result in error message:
Error in attr(attr(x[[1]], "n.apps")) : 
  either 2 or 3 arguments are required

Do you have any suggestion to what I might try? 

Thank you and all the best, 
Erle

**Comment by abdelkaderm** [comment]
Hi Erle, 
We apologize for this long delay in responding to this issue. We have not yet introduced DS for many predictors, but you can do it step by step, i.e. use a first predictor to do the analysis and repeat the same analysis based on residuals using a different predictor, and so on. Please find a recent tellus paper (http://www.tellusa.net/index.php/tellusa/article/view/25954) where we did exactly what you are asking for. You can find the script related to it in the supporting materiel.
Bests,
