### ISSUE TITLE
retrieve.ncdf4

### ISSUE THREAD

**Issue by brasmus** [metno/esd#187]
one of the examples is while trying to execute the retrieve.ncdf4 function, I come up with this error message "'retrieve.ncdf4' is not suited to extract longitude units different from 'degrees_east'", what does this mean? and how can I solve this problem? Does this mean the .nc file I have is not projected or it does not have the correct format? Also I have questions regarding the eofs. How does this package select eofs for different areas, or do we need to predefine the eofs for our interest area? I will be grateful to you if you can spare some of your time to explain this error and help me in downscaling cordex data. 
I look forward to hearing from you as soon as possible.

**Comment by abdelkaderm** [comment]
Dears,
`retrieve.ncdf4` function is not appropriate for RCM data like EURO-CORDEX, especially, when the grid is rotated. This is why you get an error message. `retrieve.ncdf4` handle only regular girds. You would better use 'retrieve.rcm' function which will consider each grid cell separately and store the irregular grid as `station` objects. This works as long as you select a small domain. For large domains, you may face some memory issues. Then do a PCA on stations to convert it to field, etc... 
In R type `? retrieve` to access the documentation. It is explained there :+1:
