### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by tanxuezhi** [metno/esd#189]
When I install esd on windows. There come up with an error:
* installing *source* package 'esd' ...
** R
Error in parse(outFile) : 
ERROR: unable to collate and parse R files for package 'esd'
* removing 'C:/Users/Tan/Documents/R/win-library/3.2/esd'
Error: Command failed (1)
Do you know the reason, and how can I solve this? Thanks

**Comment by abdelkaderm** [comment]
Hi there, 
Try installation method 2 : From GitHub using R 
Let me know if you still have a problem
Bests,
