### ISSUE TITLE
Predictors for downscaling

### ISSUE THREAD

**Issue by javakh** [metno/esd#196]
When I'm performing downscaling for precipitation using ESD during 1951-80, I'm getting a set of predictors (Say 5-6 predictors) producing good results.Now if I change the period i.e. 1961-90 or 1971-2000, i'm getting different set of predictors giving good results.Now my question is how to decide which set of predictors should be considered for future projection??

**Comment by brasmus** [comment]
You should use the predictors which are common for all periods, or you can use the longer period 1951-2000 for your model calibration.
