### ISSUE TITLE
t2m.NCEP() bug

### ISSUE THREAD

**Issue by valpesendorfer** [metno/esd#198]
Hello,

I've tried to run a couple examples from the reference pdf, and I've encountered this problem with the function `t2m.NCEP()` on multiple occasions (most recently in Example 3.8):

`> t2m <- t2m.NCEP()
Error in as.field.default(y, index(eof), lon = attr(eof, "longitude"),  : 
  unused argument (verbose = verbose)
`

Thanks

---------

version info:

version
               _                           
platform       x86_64-w64-mingw32          
arch           x86_64                      
os             mingw32                     
system         x86_64, mingw32             
status                                     
major          3                           
minor          3.2                         
year           2016                        
month          10                          
day            31                          
svn rev        71607                       
language       R                           
version.string R version 3.3.2 (2016-10-31)
nickname       Sincere Pumpkin Patch

**Comment by kajsamp** [comment]
Hi, 

Which version of esd are you using? I just updated the as.field function in the master-ncdf branch of esd. Could you update the package and see if it works? 

Kajsa

**Comment by valpesendorfer** [comment]
According to the description I'm running version 1.5, just installed with `install_github('metno/esd')`

Val

**Comment by kajsamp** [comment]
I think the bug is fixed now. It works for me anyway.

**Comment by valpesendorfer** [comment]
I can confirm it is working now ... thanks for the support!

Best,

Val
