### ISSUE TITLE
Predictors with low correction giving good downscaling results

### ISSUE THREAD

**Issue by javakh** [metno/esd#199]
For precipitation I'm getting low correlation with 500hpa Geo potential height in a pre-selected domain.
12 grid points of the selected field are showing correlations as following.
 -0.1591137	-0.08382283	0.02595841
-0.1740694	-0.09714334	0.02119386
-0.166574	-0.0961217	0.01696688
-0.1343502	-0.07319381	0.02297127
I have used corfield() function to obtain above correlations.

However, this predictor is giving a cross correlation of 0.52 while used for downscaling through DS.

Now my question is what may be the probable reason behind good downscaling results for the  predictor with low correlation??

**Comment by kajsamp** [comment]
Could you post figures showing the correlation field and the cross-correlation? A cross-correlation of 0.52 is not very high though. It could be because the EOF analysis emphasizes the signal that is relevant to the precipitation.

**Comment by javakh** [comment]
![image](https://cloud.githubusercontent.com/assets/11016843/20107984/8e4b6528-a600-11e6-951f-46e235c807ba.png)
![image](https://cloud.githubusercontent.com/assets/11016843/20108065/cda71ab4-a600-11e6-8e04-a96b19eb2981.png)

**Comment by javakh** [comment]
Cross-correlation of 0.52 is not that high but in some cases predictor with relatively higher correlation have shown cross-correlation less than 0.5.
what is the reason and how can I identify a predictor that will give high cross correlation value??

**Comment by brasmus** [comment]
It may be related to data quality. Perhaps try to apply PCA to a set of several stations? Perhaps there is only a weak dependency? You can have a look at the residuals of the regression to see if there is any "structure" in the data (eg dominant PCA modes, autocorrelation).

**Comment by javakh** [comment]
@brasmus .....Sir, the predictant is a single time seies of precipitation, so PCA is not applicable here.I'm posting the residuals.It seems there is no auto-correlation present here.
![image](https://cloud.githubusercontent.com/assets/11016843/20133570/0e884df4-a68e-11e6-97c5-002e7c633064.png)

![image](https://cloud.githubusercontent.com/assets/11016843/20133583/1ef6aa1e-a68e-11e6-96f3-d0db451261fe.png)
