### ISSUE TITLE
fail to install esd on linux cluster

### ISSUE THREAD

**Issue by Marston** [metno/esd#20]
Hi,

I've tried to install ESD on my linux cluster. The version of R:
R version 3.0.2 (2013-09-25) -- "Frisbee Sailing"
Copyright (C) 2013 The R Foundation for Statistical Computing
Platform: x86_64-unknown-linux-gnu (64-bit)

However, I've gotten this error and I don't know if it is esd that's the problem or R:
> library('devtools')
> library('ncdf4')
> install_github('metno/esd')
Downloading github repo metno/esd@master
Installing esd
'/software/apps/R/3.0.2/i1214-nomkl/lib64/R/bin/R' --vanilla CMD INSTALL  \
  '/tmp/Rtmp0MMjM8/devtools3ae8b521c3b/metno-esd-6046f68'  \
  --library='/home/sm_marst/R/x86_64-unknown-linux-gnu-library/3.0'  \
  --install-tests

* installing *source* package ‘esd’ ...
** R
Error in parse(outFile) :
  /tmp/Rtmp0MMjM8/devtools3ae8b521c3b/metno-esd-6046f68/R/DS.R:771:1: unexpected '}'
770:   invisible(ds)
771: }
     ^
ERROR: unable to collate and parse R files for package ‘esd’
* removing ‘/home/sm_marst/R/x86_64-unknown-linux-gnu-library/3.0/esd’
* restoring previous ‘/home/sm_marst/R/x86_64-unknown-linux-gnu-library/3.0/esd’
Error: Command failed (1)

**Comment by Marston** [comment]
Hi,

Apologies for the late reply. I still cannot get the package to install. But I think it is not ESD error, I think. The problem comes from ncf4 which seems to install ok, but ESD cannot find it later. Here the print out, maybe someone have run into this problem before. 

> install.packages('ncdf4')
Installing package into ‘/home/sm_marst/R/x86_64-unknown-linux-gnu-library/3.0’
(as ‘lib’ is unspecified)
trying URL 'http://ftp.sunet.se/pub/lang/CRAN/src/contrib/ncdf4_1.13.tar.gz'
Content type 'application/x-gzip' length 171897 bytes (167 Kb)
opened URL
==================================================
downloaded 167 Kb

* installing *source* package ‘ncdf4’ ...
** package ‘ncdf4’ successfully unpacked and MD5 sums checked
configure.in: starting
checking for nc-config... yes
Using nc-config: nc-config
Output of nc-config --all:

This netCDF 4.2 has been built with the following features:

  --cc        -> icc
  --cflags    ->  -I/software/apps/netcdf/4.2/i1214-hdf5-1.8.9/include -I/software/apps/hdf5/1.8.9/i1214/include
  --libs      -> -L/software/apps/netcdf/4.2/i1214-hdf5-1.8.9/lib -lnetcdf

  --cxx       -> @CXX@
  --has-c++   -> @HAS_CXX@

  --fc        -> @FC@
  --fflags    -> @FFLAGS@ @MOD_FLAG@/software/apps/netcdf/4.2/i1214-hdf5-1.8.9/include
  --flibs     -> -L/software/apps/netcdf/4.2/i1214-hdf5-1.8.9/lib @NC_FLIBS@
  --has-f77   -> @HAS_F77@
  --has-f90   -> @HAS_F90@

  --has-dap   -> no
  --has-nc2   -> yes
  --has-nc4   -> yes
  --has-hdf5  -> yes
  --has-hdf4  -> no
  --has-pnetcdf-> no
  --has-szlib ->

  --prefix    -> /software/apps/netcdf/4.2/i1214-hdf5-1.8.9
  --includedir-> /software/apps/netcdf/4.2/i1214-hdf5-1.8.9/include
  --version   -> netCDF 4.2

---
netcdf.m4: about to set rpath, here is source string: >-L/software/apps/netcdf/4.2/i1214-hdf5-1.8.9/lib -lnetcdf<
netcdf.m4: final rpath:   -Wl,-rpath,/software/apps/netcdf/4.2/i1214-hdf5-1.8.9/lib
Netcdf library version: netCDF 4.2
Netcdf library has version 4 interface present: yes
Netcdf library was compiled with C compiler: icc
configure: creating ./config.status
config.status: creating src/Makevars

**********************  Results of ncdf4 package configure *******************

netCDF v4 CPP flags      = -I/software/apps/netcdf/4.2/i1214-hdf5-1.8.9/include -I/software/apps/hdf5/1.8.9/i1214/include
netCDF v4 LD flags       =   -Wl,-rpath,/software/apps/netcdf/4.2/i1214-hdf5-1.8.9/lib -L/software/apps/netcdf/4.2/i1214-hdf5-1.8.9/lib -lnetcdf
netCDF v4 runtime path   =   -Wl,-rpath,/software/apps/netcdf/4.2/i1214-hdf5-1.8.9/lib

netCDF C compiler used   = icc
R      C compiler used   = icc -std=gnu99 -g -O2 -std=c99

******************************************************************************

** libs
icc -std=gnu99 -I/software/apps/R/3.0.2/i1214-nomkl/lib64/R/include -DNDEBUG -I/software/apps/netcdf/4.2/i1214-hdf5-1.8.9/include -I/software/apps/hdf5/1.8.9/i1214/include -I/usr/local/include    -fpic  -g -O2 -std=c99  -c ncdf.c -o ncdf.o
icc: command line warning #10121: overriding '-stdgnu99' with '-stdc99'
icc -std=gnu99 -I/software/apps/R/3.0.2/i1214-nomkl/lib64/R/include -DNDEBUG -I/software/apps/netcdf/4.2/i1214-hdf5-1.8.9/include -I/software/apps/hdf5/1.8.9/i1214/include -I/usr/local/include    -fpic  -g -O2 -std=c99  -c ncdf2.c -o ncdf2.o
icc: command line warning #10121: overriding '-stdgnu99' with '-stdc99'
icc -std=gnu99 -I/software/apps/R/3.0.2/i1214-nomkl/lib64/R/include -DNDEBUG -I/software/apps/netcdf/4.2/i1214-hdf5-1.8.9/include -I/software/apps/hdf5/1.8.9/i1214/include -I/usr/local/include    -fpic  -g -O2 -std=c99  -c ncdf3.c -o ncdf3.o
icc: command line warning #10121: overriding '-stdgnu99' with '-stdc99'
icc -std=gnu99 -I/software/apps/R/3.0.2/i1214-nomkl/lib64/R/include -DNDEBUG -I/software/apps/netcdf/4.2/i1214-hdf5-1.8.9/include -I/software/apps/hdf5/1.8.9/i1214/include -I/usr/local/include    -fpic  -g -O2 -std=c99  -c src_ncdf4.c -o src_ncdf4.o
icc: command line warning #10121: overriding '-stdgnu99' with '-stdc99'
icc -std=gnu99 -shared -L/usr/local/lib64 -o ncdf4.so ncdf.o ncdf2.o ncdf3.o src_ncdf4.o -Wl,-rpath,/software/apps/netcdf/4.2/i1214-hdf5-1.8.9/lib -L/software/apps/netcdf/4.2/i1214-hdf5-1.8.9/lib -lnetcdf -L/software/apps/R/3.0.2/i1214-nomkl/lib64/R/lib -lR
installing to /home/sm_marst/R/x86_64-unknown-linux-gnu-library/3.0/ncdf4/libs
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
* DONE (ncdf4)

The downloaded source packages are in
	‘/tmp/RtmpyE8Myg/downloaded_packages’
> 

> library('devtools')
> library('ncdf4')
> install_github('metno/esd')
Downloading github repo metno/esd@master
Installing esd
'/software/apps/R/3.0.2/i1214-nomkl/lib64/R/bin/R' --vanilla CMD INSTALL  \
  '/tmp/RtmptJS5y1/devtools73a33d286450/metno-esd-1003065'  \
  --library='/home/sm_marst/R/x86_64-unknown-linux-gnu-library/3.0'  \
  --install-tests

* installing *source* package ‘esd’ ...
** R
** data
** demo
** preparing package for lazy loading
Warning in library("ncdf", logical.return = TRUE) :
  there is no package called ‘ncdf’
Installing package into ‘/home/sm_marst/R/x86_64-unknown-linux-gnu-library/3.0’
(as ‘lib’ is unspecified)
trying URL 'http://cran.r-project.org/src/contrib//ncdf_1.6.8.tar.gz'
Content type 'application/x-gzip' length 82058 bytes (80 Kb)
opened URL
==================================================
downloaded 80 Kb

* installing *source* package ‘ncdf’ ...
** package ‘ncdf’ successfully unpacked and MD5 sums checked
checking for nc-config... /software/apps/netcdf/4.2/i1214-hdf5-1.8.9/bin/nc-config
configure: creating ./config.status
config.status: creating src/Makevars
** libs
icc -std=gnu99 -I/software/apps/R/3.0.2/i1214-nomkl/lib64/R/include -DNDEBUG -I/software/apps/netcdf/4.2/i1214-hdf5-1.8.9/include -I/software/apps/hdf5/1.8.9/i1214/include -I/usr/local/include    -fpic  -g -O2 -std=c99  -c ncdf.c -o ncdf.o
icc: command line warning #10121: overriding '-stdgnu99' with '-stdc99'
icc -std=gnu99 -I/software/apps/R/3.0.2/i1214-nomkl/lib64/R/include -DNDEBUG -I/software/apps/netcdf/4.2/i1214-hdf5-1.8.9/include -I/software/apps/hdf5/1.8.9/i1214/include -I/usr/local/include    -fpic  -g -O2 -std=c99  -c ncdf2.c -o ncdf2.o
icc: command line warning #10121: overriding '-stdgnu99' with '-stdc99'
icc -std=gnu99 -I/software/apps/R/3.0.2/i1214-nomkl/lib64/R/include -DNDEBUG -I/software/apps/netcdf/4.2/i1214-hdf5-1.8.9/include -I/software/apps/hdf5/1.8.9/i1214/include -I/usr/local/include    -fpic  -g -O2 -std=c99  -c ncdf3.c -o ncdf3.o
icc: command line warning #10121: overriding '-stdgnu99' with '-stdc99'
icc -std=gnu99 -shared -L/usr/local/lib64 -o ncdf.so ncdf.o ncdf2.o ncdf3.o -L/software/apps/netcdf/4.2/i1214-hdf5-1.8.9/lib -lnetcdf -L/software/apps/R/3.0.2/i1214-nomkl/lib64/R/lib -lR
installing to /home/sm_marst/R/x86_64-unknown-linux-gnu-library/3.0/ncdf/libs
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
Error in dyn.load(file, DLLpath = DLLpath, ...) :
  unable to load shared object '/home/sm_marst/R/x86_64-unknown-linux-gnu-library/3.0/ncdf/libs/ncdf.so':
  libnetcdf.so.7: cannot open shared object file: No such file or directory
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/home/sm_marst/R/x86_64-unknown-linux-gnu-library/3.0/ncdf’
Warning in install.packages("ncdf", contriburl = "http://cran.r-project.org/src/contrib/") :
  installation of package ‘ncdf’ had non-zero exit status

The downloaded source packages are in
	‘/tmp/RtmpoY7Xnk/downloaded_packages’
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
* DONE (esd)
>

**Comment by brasmus** [comment]
Hi Marston, I see that it wants the package 'ncdf' which is now redundant. We'll try to fix the problem by removing it fairly promptly. First we need a cup of coffee ;-)

**Comment by Marston** [comment]
Hi Rasmus,

Hope you guys had a great holiday. Yes, I saw that afterwards that the problem was ncdf vs ncdf4. I tried to install it but the package is no longer available. Great if you could fix this problem.

/M

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Marston S. Johnston, PhD
Department of Earth Sciences
University of Gothenburg, Sweden
Email: marston.johnston@gu.se <mailto:marston.johnston@gu.se> 
Phone: +46-31-7862859 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Only the fruitful thing is true!

**Comment by abdelkaderm** [comment]
Dear Marston,

I have removed redundancy caused by `ncdf` library. Try to reinstall the `esd` package now as

`> install_github('metno/esd')`

I hope it will work.

 Abdelkader

**Comment by Marston** [comment]
Hi,

It works fine now:

install_github('metno/esd')
Downloading github repo metno/esd@master
Installing esd
'/software/apps/R/3.0.2/i1214-nomkl/lib64/R/bin/R' --vanilla CMD INSTALL  \
  '/tmp/RtmpzEHQar/devtools83fa5d454ad2/metno-esd-1ef5297'  \
  --library='/home/sm_marst/R/x86_64-unknown-linux-gnu-library/3.0'  \
  --install-tests

* installing *source* package ‘esd’ ...
** R
** data
** demo
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
* DONE (esd)
>

Appreciate it!
/M

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Marston S. Johnston, PhD
Department of Earth Sciences
University of Gothenburg, Sweden
Email: marston.johnston@gu.se <mailto:marston.johnston@gu.se> 
Phone: +46-31-7862859 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Only the fruitful thing is true!
