### ISSUE TITLE
How to interpret the CCA maps and time series?

### ISSUE THREAD

**Issue by MeJitendra** [metno/esd#200]
Hello Sir,
I wish to know, How to interpret the CCA maps and time series? How to decide whether the predictor is suitable or not from CCA map and time series? 
![cca-plot](https://cloud.githubusercontent.com/assets/11473497/20169120/c8362d9e-a74b-11e6-844f-c80ecac698cc.jpg)
Regards

**Comment by brasmus** [comment]
Quite impressive correlations between the wind speed over the Indian ocean and the precipitation. But I doubt that the GCMs will be able to provide a realistic description of the 10-m wind field, especially over the Himalayas and the land ara. The large predictor-domain is likely going to introduce unwanted effects from GCMs and dilute the signal. Perhaps better to limit the domain to the ocean or apply a land-sea mask? (`mask(x,land=TRUE)`) I wonder whether the wind speed picks up increased evaporation which subsequently affects the rainfall...? You should try with `DS`and look at the cross-validation results.
