### ISSUE TITLE
Use of weights in DS function

### ISSUE THREAD

**Issue by javakh** [metno/esd#203]
It is a little query from me rather than an issue.

Why it is necessary to use weights in DS function???What may happen if I don't use weights??
weights are defined as: **1/coredata(attr(y,'standard.error')**
what does 'standard.error' indicates here??

Please reply.

**Comment by brasmus** [comment]
Weighting in DS can be turned off by setting its argument `weight=FALSE`. The `weight` option uses standard errors from aggregated quantities (e.g. the seasonal mean) to set the weights. These depend on the sample standard deviation and the sample size. Hence, years with few valid data points and greater standard deviation will have a lesser effect on the regression results compared to years with large sample size and weak standard deviation. The weights are a part of the `lm` method.
