### ISSUE TITLE
DS error with modified field

### ISSUE THREAD

**Issue by ogamimusashi** [metno/esd#205]
Both my station (discharge meansurements) and field (geopotential heights) are 492 months long. 

My station has been build with station() but my field is different. It was imported via retrieve.ncdf4() (as a 31*53*492 field) then exported to matlab where it was interpolated then processed. I finally imported the processed field back to R as a 301*521*492 array that i reshaped into a 492*(301*521) matrix. 

I then used as.field(new_field,lat=lat,lon=lon,index=index(old_field)...) to convert to field.

EOF(new_field) works but DS(station,new_field) doesn't it throws the error:

Error in data.frame(y = coredata(y), X = as.matrix(coredata(X)), weights = weights) : 
  arguments imply differing number of rows: 492, 2

I understand what it means but i don't see why because doing nrow(coredata(y)) brings 492 and nrow(matrix(coredata(X)) does the same.

Any help?

DS(old_field,station) works. The only difference between old_field and new_field, appart from the values, is that one is 31*53 and the other is 301*521 for latitude and longitude.

**Comment by brasmus** [comment]
Hi,

Have you tried `plot(EOF(new_field))` and `plot(station)`? Also check `class(.)` and `index(.)` (here '.' is the object name). 

Also, I presume you use EOFs as predictor? 

In general, it's wise to inspect the various aspects of the data, plot and see what it looks like. Make sure it is what you think it is.

**Comment by ogamimusashi** [comment]
Dear Rasmus,

Yes plot(new_field) and plot(station) both work. class(new_field) gives "field" "month" "zoo" and index gives Y-m-d date vector.

I wasn't necessarily to use EOF as predictor but doing DS on the field gives me an "X not eof" type of error.

To give more precisions, my new_field is the original field with only some relevant areas kept, the rest being put to zero and those areas change for each time step.

i thought this would be the reason but while using old_field from R works using the same old_field but reimported from matlab (is was exported to matlab before being processed) doesn't.

Maybe there's something with the as.field() method that is missed?

**Comment by brasmus** [comment]
It is important that both the station and field have the same type of index, and that the timescale description in their class match. Also, I always use EOFs in my DS-calls. 
I's use `subset` to extract a smaller part of the field, rather than setting the matrix element to zero. 
But, I suggest you try different diagnostics, such as `map`. If you do not succeed, you can list your code and provide some graphics on this thread.
