### ISSUE TITLE
Questions about opening nc, thanks

### ISSUE THREAD

**Issue by duan2008** [metno/esd#207]
Sorry to disturb you. I just have a simple question when I used esd package to deal with netcdf files.
         I just got the following errors:
gcm <-retrieve("cdd_yr_HPB_NAT_m001_1951-2010.nc",param="cddETCCDI")
[1] "Warning : Calendar attribute has not been found in the meta data"
Error in check.ncdf(ncid, param = param, verbose = verbose) : 
  Frequency could not be found, neither detected, the data might be corrupted !
> gcm <-retrieve("cdd_yr_HPB_NAT_m001_1951-2010.nc",param="cddetccdi")
Error in ncid$var[[]] : invalid subscript type 'symbol'
> ncid <- nc_open('cdd_yr_HPB_NAT_m001_1951-2010.nc')
> x <- ncvar_get(ncid,'cddetccdi')
[1] "vobjtovarid4: error #F: I could not find the requsted var (or dimvar) in the file!"
[1] "var (or dimvar) name: cddetccdi"
[1] "file name: cdd_yr_HPB_NAT_m001_1951-2010.nc"
Error in vobjtovarid4(nc, varid, verbose = verbose, allowdimvar = TRUE) : 
  Variable not found
> x <- ncvar_get(ncid,'cddETCCDI')
> lon <-  ncvar_get(ncid,'lon')
> lat <-  ncvar_get(ncid,'lat')
> tim <-  ncvar_get(ncid,'time')
> map(x,colorbar=FALSE)
 num [1:116, 1:71] 143 143 144 138 126 ...
Error in order(lon(x)) : argument 1 is not a vector

       The attributes of the nc file are as follows:

> nc

**Comment by kajsamp** [comment]
It's difficult to reproduce the problem without the data. What does the file contain?  Can you run the function with verbose=TRUE and post the results here?

Thanks,
Kajsa
