### ISSUE TITLE
GCMs giving poor downscaling results

### ISSUE THREAD

**Issue by javakh** [metno/esd#208]
I have selected some NCEP predictors over my study region which are giving very good downscaling results( cross-correlation >0.6).
But when I'm using same predictors from CMIP5 models they are giving downscaled results with poor correlation. Even use of combined EOF of GCM and NCEP is not improving the results much ( correlation <0.2)
In this context how can I improve my downscaled results?
Thanks.

**Comment by kajsamp** [comment]
The cross-validation is relevant only to assess the downscaling model tuned to reanalysis data. Reanalysis is based on observations and there has to be a link between local and large scale climate climate for the statistical downscaling to have any skill. This is what the cross-validation tests. GCMs on the other hand are not supposed to reproduce historical weather so the comparison between observed and GCM generated values for a given date is pointless. 

To evaluate how well the downscaling model (which has been tuned with reanalysis data as a predictor) works when applied to GCM data, you can study 1) the common EOF of the GCM and reanalysis, and 2) the spread of the ensemble of downscaled values based on GCMs.

**Comment by javakh** [comment]
Thanks for your answer. Can you please suggest what kind of study may be done with common eof. What type of validation metrics may be used to evaluate downscaling models?
Secondly, what may be the added value of ESD? Simple bias corrections like quantile mapping can  reproduce observed mean,variance ,CDFs etc quite well.What may the advantage of ESD?

Thanks.

**Comment by brasmus** [comment]
Please see Benestad, R.E. (2001) A comparison between two empirical downscaling strategies, Int. J. Climatology,Vol 21, Issue 13, pp.1645-1668. [DOI 10.1002/joc.703]: http://www.google.com/url?q=http%3A%2F%2Fwww3.interscience.wiley.com%2Fcgi-bin%2Fabstract%2F88511304%2FABSTRACT&sa=D&sntz=1&usg=AFQjCNGk2BGOFuC7aKbx6WsmgYWJyh3PDg. Also see `diagnose`in `esd`
