### ISSUE TITLE
Here is a question I got:

### ISSUE THREAD

**Issue by brasmus** [metno/esd#211]
_I have for example a data set with observed temperatures of a station X (predictor) from 1980 – 2010 and I have CMIP5 output  for a climate model from 1980 – 2100. Let us say I want to use  an monthly EOF of the air temperature of the GCM as predictand. I can then do a downscaling like in example 5.1 in the [MET report](https://figshare.com/articles/_esd_The_Empirical_Statistical_Downscaling_tool_amp_its_visualisation_capabilities_/1454425), but how do I extend this then into the future? And secondly, what if my station data is daily and my climate model data is monthly?_

The calibration needs to involve a reanalysis (a third data set). E.g. [NCEP/NCAR reanalysis 1](ftp://ftp.cdc.noaa.gov/Datasets/ncep.reanalysis.derived/surface/air.mon.mean.nc). The recommended approach is to use common EOFs. Something like this:

```r2
X <- combine(reanalysis, GCM)
commoneof <- EOF(X)
ds <- DS(station,commoneof)
plot(ds)
```

_Is there an code example available that illustrates this? I tried to find it on GitHub but I could not. I also tried to get the DSensemble example (p35, esd.pdf)  to work, but I could not because I do not have the file air.2m.mon.mean.nc (predictor)._

The only difference is that you combine the reanalysis with the GCM and apply EOF to this combined field. This is done automatically in DSensemble. But you need to give it a predictor for calibration. Any reanalysis with monthly data and a reasonably long record in the netCDF format (CF conventions) will do - you only need to set predictor to the name of this file.

**Comment by wimmerzeel** [comment]
Dear Rasmus,

Now I understand. Thanks.
