### ISSUE TITLE
Unable to read GCMs containing SST data

### ISSUE THREAD

**Issue by javakh** [metno/esd#215]
Getting following error while retrieving GCMs containing SST data:

> x=retrieve('tos_Omon_IPSL-CM5A-MR_historical_r1i1p1_185001-200512.nc',lon=c(-170,-120),lat=c(-5,5),it=c(1951,2005))
Error in if (substr(varid, 1, 1) == "/") stop(paste("Error, I was given a name that starts with a slash; fully qualified names NEVER start with a slash (this is required for backwards compatability).  Leave off the leading slash!")) : 
  argument is of length zero

> x=retrieve('tos_Omon_IPSL-CM5A-MR_historical_r1i1p1_185001-200512.nc',lon=c(-170,-120),lat=c(-5,5),it=c(1951,2005),param='tos')
Error in if (substr(varid, 1, 1) == "/") stop(paste("Error, I was given a name that starts with a slash; fully qualified names NEVER start with a slash (this is required for backwards compatability).  Leave off the leading slash!")) : 
  argument is of length zero

Please help to solve the issue.

**Comment by abdelkaderm** [comment]
Hi Javed

You need to specify the name of the variable to retrieve in parameter argument. 

Use summary.ncdf function to get a summary about the netcdf attributes

**Comment by javakh** [comment]
Dear Sir,
Firstly,Even without parameter argument , I am not been able to retrieve these files 
x=retrieve('tos_Omon_IPSL-CM5A-MR_historical_r1i1p1_185001-200512.nc',lon=c(-170,-120),lat=c(-5,5),it=c(1951,2005))
Error in if (substr(varid, 1, 1) == "/") stop(paste("Error, I was given a name that starts with a slash; fully qualified names NEVER start with a slash (this is required for backwards compatability). Leave off the leading slash!")) :
argument is of length zero

2ndly, the name of the variable is 'tos'; so the 'param' argument may not be wrong.

There may be some other problems.

**Comment by abdelkaderm** [comment]
The summary looks ok . Can you send me the file or a link to the file and I will try to figur out what is wrong

**Comment by javakh** [comment]
Dear Sir,
I have sent in your email via google drive - the SST file from CMCC-CM similar to the file posted in Github . Kindly check it.

**Comment by abdelkaderm** [comment]
Hi there, I got your email and checked the file. The structure of the file is not suitable for retrieve and you may need to create a field object yourself using as.field() function and nc4:: functionalities to read and put attributes.

**Comment by javakh** [comment]
Thank you sir. This seems quite complicated to me. Can you kindly give me a small example about how to do it.
