### ISSUE TITLE
confusion regarding as.station.dsensemble

### ISSUE THREAD

**Issue by kajsamp** [metno/esd#217]
There are two similar functions that can be applied to different dsensemble objects,

1) 'as.station.dsensemble.pca' - transforms a PCA based dsensemble object into a **list** where each element represents one station and contain downscaled values for **all ensemble members**, and

2) 'as.station.dsensemble.station' - transforms a station based dsensemble object (like the output of function 1) into a **station object** with a single time series for each station **aggregated over the ensemble members** (e.g., the ensemble mean or 95th percentile). 

This leads to some confusion when you apply as.station to a dsensemble object, as this can give you either a **list** or a **station object** depending on the exact type of input. In a way it makes more sense to obtain a station object when you use a function called as.station, but the list contains information about individual ensemble members that can be useful in many situations. 

I think the easiest solution would be to reserve as.station for the transformation of the PCA based dsensemble object to a station based dsensemble object, i.e., the list that includes all the GCM data. This function corresponds to the as.field.dsensemble.eof function which transforms EOF based dsensemble objects to fields (a list of fields for every GCM). The second function ('as.station.dsensemble.pca') could instead be called aggregate.dsensemble.station, referring to aggregating the results over the GCMs.

Another possible solution is to change the name of 'as.station.dsensemble.pca' to 'as.dsensemble.station.pca' or 'as.dsensemble.station', referring to the transformation of a dsensemble-PCA object to a dsensemble-station object. 

What do you think? I haven't implemented any changes yet and the two functions are not causing any major problems at the moment, but it could potentially be confusing.

Kajsa

**Comment by brasmus** [comment]
Perhaps both `as.dsensemble.station.pca` or `as.dsensemble.station` (return **dsensemble** objects) and `aggregate.dsensemble.station` + `as.station.dsensemble` (this returns a **station** object)?

**Comment by kajsamp** [comment]
If we go for this approach then we should also make the corresponding changes for dsensemble EOF and field objects. That is, as.field.dsensemble.eof should be as.dsensemble.field.eof and/or as.dsensemble.field and we should add two new functions - aggregate.dsensemble.field and as.field.dsensemble - that return a field aggregated over the gcms.
