### ISSUE TITLE
How to convert .nc4 file to .nc file 

### ISSUE THREAD

**Issue by MeJitendra** [metno/esd#219]
Sir,
I want to convert the .nc4 file to .nc file which can be further used in R for plotting maps etc.
A sample file can be collected from the website- https://data.giss.nasa.gov/impacts/agmipcf/agmerra/ 

Thanks in advance.

**Comment by brasmus** [comment]
Why not just read i straight into R. .nc4-files are netCDf4, and can be read using `library(ncdf4)` or the default version of `esd`(using ncdf4 rather than ncdf).
