### ISSUE TITLE
ds.ensembles

### ISSUE THREAD

**Issue by brasmus** [metno/esd#227]
Need to check

`as.station.dsensemble`
`as.station.dsensemble.pca`
`as.station.dsensemble.station`

**Comment by Attia81** [comment]
R session is aborted when I use the function  DSensemble.t2m 

#Downscale the temperature in Oslo 
```
rcp4.5 <- DSensemble.t2m(Oslo, path="D:/",rcp='rcp45', pattern="tas_Amon_",
                         biascorrect=TRUE, predictor ="D:/air.2m.mon.mean.nc",
                         plot=F, verbose=TRUE)
```

**Comment by abdelkaderm** [comment]
Hi, you may have an issue with the memory. Can you try with few GCMs. You can specify this by adding  the argument 'select = 1:3' to do the downscaling for the first three GCM runs.

Ak

**Comment by Attia81** [comment]
Hi

I tried the suggested solution but didn't work. I work on windows, I try to
run it on Linux

Thanks

**Comment by abdelkaderm** [comment]
Well, it should work for both Linux and windows platforms. Can you send the verbose outputs and error message and where it stops ...

**Comment by Attia81** [comment]
Ok,on windows, I get the error message as shown in the attached screenshot

On linux, I get the following error
#code
rcp4.5 <- DSensemble.t2m(Oslo,
path="~",rcp='tas_Amon_FIO-ESM_rcp45_000.nc',
pattern="tas_Amon_ens_",biascorrect=TRUE, predictor ="air.2m.mon.mean.nc",
                         plot=T, verbose=T,select=1:3)
#error

[1] "Reading data for t2m"
[1] "Sort Longitudes"
[1] "Sort Latitudes"
[1] "Data converted to unit: degC"
[1] "0 missing values have been replaced by NA"
[1] "Done !"
[1] "dimensions"
[1]  57  29 484
[1] "Aggregate seasonal values"
[1] "Retrieve & arrange GCMs"
[1] "GCMs:"
[1] "~/tas_Amon_FIO-ESM_rcp45_000.nc"
character(0)
[1] "Set up results matrix & table of diagnostics"
[1] "Quick test"
[1] "loop..."
[1] NA
[1] "retrieve.default"
Error in if ((!is.character(filename)) || (nchar(filename) < 1))
stop("Passed a filename that is NOT a string of characters!") :
  missing value where TRUE/FALSE needed
In addition: Warning messages:
1: In DSensemble.t2m(Oslo, path = "~", rcp =
"tas_Amon_FIO-ESM_rcp45_000.nc",  :
  station is not daily data
2: In list(...) : closing unused connection 3 (DSensemble.t2m-log.txt)

Maybe missing values 'NA' are causing the error on Linux

Many thanks

**Comment by brasmus** [comment]
It seems to me that you are not looking in the right folder since you got 'character(0)' and 'NA' after loop. On the other hand, there is one file name provided (If you only have one GCM, then there is no point in using 'DSensemble' and that may be one cause for the lack of success). Alternatively, your naming convention does not fit the one assumed by the function. You should see a list of names of the files with GCM results.

**Comment by Attia81** [comment]
Worked well, thank you very much. Passing one GCM was the problem...
