### ISSUE TITLE
Issue with predict.ds

### ISSUE THREAD

**Issue by javakh** [metno/esd#228]
Dear Sir,
I have calibrated downscaling model for rainfall using combined EOF of  reanalysis and GCM during 1951-80. Then predicted rainfall using GCM data during 1981-2005 through predict.ds() function. In this process I have observed two issues:
1. some negative rainfall values have been obtained.during prediction period.
2. mean rainfall have been same in both period 1951-80 and 1981-2005.
What wrong I'm doing here? Please help me.
The code is given below:

> y1=subset(nci_jjas,it=1951:1980) ## predictand data (monsoon rainfall)
> str(y1)
‘zoo’ series from 1951-06-01 to 1980-09-01
  Data: atomic [1:120] 146 252 280 184 227 ...
 - attr(*, "unit")= chr "mm"
 - attr(*, "variable")= chr "pr"
 - attr(*, "history")=List of 3
  ..$ call     :List of 3
  .. ..$ : language station.subset(x, it = it, is = is, verbose = verbose)
  .. ..$ : language station.subset(x, it = it, is = is, verbose = verbose)
  .. ..$ : language station.subset(x, it = it, is = 1, verbose = verbose)
  ..$ timestamp: chr [1:3] "Mon Oct 30 15:54:08 2017" "Mon Oct 30 15:54:08 2017" "Mon Oct 30 15:58:05 2017"
  ..$ session  :List of 3
  .. ..$ R.version  : chr "R version 3.2.3 (2015-12-10)"
  .. ..$ esd.version: chr "esd_1.7001"
  .. ..$ platform   : chr "x86_64-w64-mingw32/x64 (64-bit)"
  Index:  Date[1:120], format: "1951-06-01" "1951-07-01" "1951-08-01" "1951-09-01" "1952-06-01" "1952-07-01" "1952-08-01" "1952-09-01" "1953-06-01" "1953-07-01" ...
> ncep_jjas=subset(ncep,it='jjas') ## reanalysis during monsoon
> x1=subset(ncep_jjas,it=1951:1980)
> str(x1)
‘zoo’ series from 1951-06-01 to 1980-09-01
  Data: num [1:120, 1:12] 39.5 49.8 49.8 41 40.7 ...
 - attr(*, "variable")= chr "pr_wtr"
 - attr(*, "longname")= chr "Monthly Mean of Precipitable Water Content"
 - attr(*, "units")= chr "kg/m^2"
 - attr(*, "longitude")= num [1:4(1d)] 80 82.5 85 87.5
 - attr(*, "greenwich")= logi FALSE
 - attr(*, "latitude")= num [1:3(1d)] 22.5 25 27.5
 - attr(*, "file")= chr "pr_wtr.mon.mean.nc"
 - attr(*, "title")= chr "monthly mean pr_wtr.eatm from the NCEP Reanalysis"
 - attr(*, "source")= chr "monthly"
 - attr(*, "experiment_id")= chr "pr_wtr.eatm"
 - attr(*, "timeunit")= chr "month"
 - attr(*, "type")= chr "mean"
 - attr(*, "URL")= chr "http://climexp.knmi.nl/"
 - attr(*, "call")= language retrieve.ncdf4(ncfile = "pr_wtr.mon.mean.nc")
 - attr(*, "institution")= logi NA
 - attr(*, "reference")= logi NA
 - attr(*, "history")=List of 3
  ..$ call     :List of 4
  .. ..$ : language retrieve.ncdf4("pr_wtr.mon.mean.nc")
  .. ..$ : language subset.field(ncep_new[[23]], is = list(lon = c(80, 88), lat = c(21, 29)))
  .. ..$ : language subset.field(ncep, it = "jjas")
  .. ..$ : language subset.field(ncep_jjas, it = 1951:1980)
  ..$ timestamp: chr [1:4] "Fri May 27 10:25:11 2016" "Mon Oct 30 15:54:08 2017" "Mon Oct 30 15:58:05 2017" "Mon Oct 30 15:58:05 2017"
  ..$ session  :List of 3
  .. ..$ R.version  : chr "R version 3.2.3 (2015-12-10)"
  .. ..$ esd.version: chr "esd_1.7001"
  .. ..$ platform   : chr "x86_64-w64-mingw32/x64 (64-bit)"
 - attr(*, "dimensions")= int [1:3] 4 3 120
  Index:  Date[1:120], format: "1951-06-01" "1951-07-01" "1951-08-01" "1951-09-01" "1952-06-01" "1952-07-01" "1952-08-01" "1952-09-01" "1953-06-01" "1953-07-01" ...
> gcm_ncep=regrid(gcm_predictors,is=ncep_jjas) ## GCM regrided on NCEP grid
> gcm=subset(gcm_ncep,is=list(lon=c(80,88),lat=c(21,29)))
> gcm_jjas=subset(gcm,it='jjas')
> str(gcm_jjas)
‘zoo’ series from 1950-06-01 to 2005-09-01
  Data: num [1:224, 1:12] 36.1 50.2 52.3 43.8 29.3 ...
 - attr(*, "variable")= chr "prw"
 - attr(*, "longname")= chr "Water Vapor Path"
 - attr(*, "units")= chr "kg m-2"
 - attr(*, "longitude")= num [1:4] 80 82.5 85 87.5
 - attr(*, "greenwich")= logi FALSE
 - attr(*, "latitude")= num [1:3] 22.5 25 27.5
 - attr(*, "calendar")= chr "noleap"
 - attr(*, "file")= chr "E:/BCCI.m/prw_Amon_bcc-csm1-1-m_historical_r1i1p1_185001-201212.nc"
 - attr(*, "title")= chr "bcc-csm1-1-m model output prepared for CMIP5 historical"
 - attr(*, "source")= chr "CMIP5"
 - attr(*, "model_id")= chr "bcc-csm1-1-m"
 - attr(*, "experiment_id")= chr "historical"
 - attr(*, "realization")= int 1
 - attr(*, "timeunit")= chr "month"
 - attr(*, "type")= chr "model"
 - attr(*, "URL")= chr "http://climexp.knmi.nl/"
 - attr(*, "call")= language retrieve.ncdf4(ncfile = ncfile, path = path, param = param, lon = ..1, lat = ..2, it = ..3, verbose = verbose)
 - attr(*, "institution")= logi NA
 - attr(*, "reference")= logi NA
 - attr(*, "history")=List of 3
  ..$ call     :List of 6
  .. ..$ : language retrieve.ncdf4(ncfile, path = path, param = param, verbose = verbose, ...)
  .. ..$ : language g2dl.field(x, greenwich = FALSE)
  .. ..$ : language subset.field(x, is = list(lon = c(floor(min(lon.new)) - 10, ceiling(max(lon.new)) + 10), lat = c(floor(min(lat.new)) - 10, ceiling(max(lat.new)) + 10)))
  .. ..$ : language regrid.field(gcm_predictors[[23]], is = ncep_new[[23]])
  .. ..$ : language subset.field(gcm_ncep, is = list(lon = c(80, 88), lat = c(21, 29)))
  .. ..$ : language subset.field(gcm, it = "jjas")
  ..$ timestamp: chr [1:6] "Sat Dec 31 19:37:55 2016" "Mon Oct 30 16:03:51 2017" "Mon Oct 30 16:03:51 2017" "Mon Oct 30 16:04:17 2017" ...
  ..$ session  :List of 3
  .. ..$ R.version  : chr "R version 3.2.3 (2015-12-10)"
  .. ..$ esd.version: chr "esd_1.7001"
  .. ..$ platform   : chr "x86_64-w64-mingw32/x64 (64-bit)"
 - attr(*, "dimensions")= int [1:3] 4 3 224
  Index:  Date[1:224], format: "1950-06-01" "1950-07-01" "1950-08-01" "1950-09-01" "1951-06-01" "1951-07-01" "1951-08-01" "1951-09-01" "1952-06-01" "1952-07-01" ...
> z1=subset(gcm_jjas,it=1951:1980) ## Calibration data of GCM
> z2=subset(gcm_jjas,it=1981:2005) ## Validation data of GCM
> comb=combine(x1,z1) ## combination of reanalysis and GCM on calibration period
> eof=EOF(comb)
> ds=DS(y1,eof)
> new=predict.ds(ds,newdata=EOF(z2))
> mean(new)
[1] 250.655
> mean(ds)
[1] 250.655
> new
   1981-06-01    1981-07-01    1981-08-01    1981-09-01    1982-06-01    1982-07-01    1982-08-01    1982-09-01    1983-06-01    1983-07-01    1983-08-01 
 131.40327727  461.30201598  525.58418656  165.94039720  -55.29152398  449.28510664  387.43236062  172.51622655 -152.27245926  280.68255963  141.28314603 
   1983-09-01    1984-06-01    1984-07-01    1984-08-01    1984-09-01    1985-06-01    1985-07-01    1985-08-01    1985-09-01    1986-06-01    1986-07-01 
  14.87644013  -18.88822549  333.68681386  405.56407480  222.48648137   96.85949307  365.51372953  367.84321705  234.37233815  267.63242939  447.21305947 
   1986-08-01    1986-09-01    1987-06-01    1987-07-01    1987-08-01    1987-09-01    1988-06-01    1988-07-01    1988-08-01    1988-09-01    1989-06-01 
 327.18689643  154.66326026  353.55288747  374.38980719  318.86603503  243.86520486   92.89873935  374.25164014  422.22326984  144.59145022   38.07581718 
   1989-07-01    1989-08-01    1989-09-01    1990-06-01    1990-07-01    1990-08-01    1990-09-01    1991-06-01    1991-07-01    1991-08-01    1991-09-01 
 394.83587273  434.18733254  240.82859231   17.62448565  401.33763489  355.16934590  256.80028458   27.88850623  381.33299020  540.53014591  205.87460263 
   1992-06-01    1992-07-01    1992-08-01    1992-09-01    1993-06-01    1993-07-01    1993-08-01    1993-09-01    1994-06-01    1994-07-01    1994-08-01 
-201.04980010  -19.01541897  342.12865644  189.87074662   15.83841323  442.95989041  423.55193152   77.17910113  100.48704161  390.24943889  362.69511979 
   1994-09-01    1995-06-01    1995-07-01    1995-08-01    1995-09-01    1996-06-01    1996-07-01    1996-08-01    1996-09-01    1997-06-01    1997-07-01 
 274.47261210  -10.54969561  429.40420649  285.17495107   96.68498147    0.07641195  348.59603102  327.50271763  146.39672231  294.39224023  494.72311407 
   1997-08-01    1997-09-01    1998-06-01    1998-07-01    1998-08-01    1998-09-01    1999-06-01    1999-07-01    1999-08-01    1999-09-01    2000-06-01 
 322.25051025  155.59728846  -57.57077813  205.66956687  460.94327179   20.81459255  364.04372963  482.11553737  404.89288505  158.36429140  196.55832710 
   2000-07-01    2000-08-01    2000-09-01    2001-06-01    2001-07-01    2001-08-01    2001-09-01    2002-06-01    2002-07-01    2002-08-01    2002-09-01 
 398.38567143  446.12019501  260.98811656   80.81853948  498.06070372  411.32100838  325.24113085 -148.03478947  298.18570916  421.33668206   76.43093811 
   2003-06-01    2003-07-01    2003-08-01    2003-09-01    2004-06-01    2004-07-01    2004-08-01    2004-09-01    2005-06-01    2005-07-01    2005-08-01 
 118.31734144  439.55437020  371.95442793  311.34830036  131.37072419  243.75631363  232.49727283  165.73792491   81.07253841  393.05615274  445.22515926 
   2005-09-01 
 191.30698710

**Comment by abdelkaderm** [comment]
Hi Javed, 
I had a quick look at the results. My guess is that your `y1` variable is not a station object and lacks some mandatory arguments such as longitude and latitude. Can you double check this and send me the output of `tr(y1)` again together with `class(y1)`. Thanks

**Comment by javakh** [comment]
> class(y1)
[1] "station" "month"   "zoo"    
> str(y1)
‘zoo’ series from 1951-06-01 to 2005-09-01
  Data: atomic [1:220] 146 252 280 184 227 ...
 - attr(*, "unit")= chr "mm"
 - attr(*, "variable")= chr "pr"
 - attr(*, "history")=List of 3
  ..$ call     :List of 1
  .. ..$ : language station.subset(x, it = it, is = 1, verbose = verbose)
  ..$ timestamp: chr "Tue Oct 31 20:36:41 2017"
  ..$ session  :List of 3
  .. ..$ R.version  : chr "R version 3.2.3 (2015-12-10)"
  .. ..$ esd.version: chr "esd_1.5"
  .. ..$ platform   : chr "x86_64-w64-mingw32/x64 (64-bit)"
 - attr(*, "latitude")= num 25
 - attr(*, "longitude")= num 84
  Index:  Date[1:220], format: "1951-06-01" "1951-07-01" "1951-08-01" "1951-09-01" "1952-06-01" "1952-07-01" "1952-08-01" "1952-09-01" "1953-06-01" "1953-07-01" "1953-08-01" "1953-09-01" "1954-06-01" ...
> 
I have put lon and lat arguments in y1 but the results are same.

**Comment by abdelkaderm** [comment]
Can you send the output of `plot(ds)` ?

**Comment by javakh** [comment]
![image](https://user-images.githubusercontent.com/11016843/32233219-ebe5b39e-be7f-11e7-8b90-e36ba159ee9f.png)

**Comment by javakh** [comment]
I have also checked the same with june temperature bjornholt station provided in esd package. But there is no difference of mean in two periods.

> bjr_mon=aggregate(bjornholt,by=as.yearmon)
> bjr_mon=zoo(bjr_mon,order.by=seq(as.Date("1883-01-01"),as.Date("2017-04-01"),'month'))
> class(bjr_mon)= c('station','month','zoo')
> attr(bjr_mon,'unit')='mm'
> attr(bjr_mon,'variable')='pr'
> attr(bjr_mon,'longitude')=10.7
> attr(bjr_mon,'latitude')=59.9
> bjr_june=subset(bjr_mon,it='june')
> bjr_june_cal=subset(bjr_june,it=1951:1980)
> bjr_june_val=subset(bjr_june,it=1981:2005)
> T2M_GCM <- subset(t2m.NorESM.M(lon=c(-10,30),lat=c(50,70)),it='june')
> T2M_NCEP <- subset(t2m.NCEP(lon=c(-10,30),lat=c(50,70)),it='june')
> T2M_GCM=regrid(T2M_GCM,is=T2M_NCEP)
> T2M_NCEP_cal=subset(T2M_NCEP,it=1951:1980)
> T2M_GCM_cal=subset(T2M_GCM,it=1951:1980)
> T2M_GCM_val=subset(T2M_GCM,it=1981:2005)
> comb=combine(T2M_NCEP_cal,T2M_GCM_cal)
> ceof=EOF(comb)
> ds=DS(bjr_june_cal,ceof)
> new=predict.ds(ds,EOF(T2M_GCM_val))
> mean(new)
[1] 3.112667
> mean(ds)
[1] 3.112667

**Comment by brasmus** [comment]
In general, any discrepancy may be due to different covariance structures in the reanalysis and the GCM for the predictands. You can test this through `diagnose(ceof)`. The common EOF gives an evaluation of the predictors. The results need to be checked, and negative values for precipitation is an indicator that the calculations have some issues that need to be dealt with. Maybe the problem can be fixed with `biasfix(ceof)`before DS. Or try different domain/GCM etc. 

Here, the lines are not correct: 

```r2
z1=subset(gcm_jjas,it=1951:1980) ## Calibration data of GCM
z2=subset(gcm_jjas,it=1981:2005) ## Validation data of GCM
comb=combine(x1,z1) ## combination of reanalysis and GCM on calibration period
eof=EOF(comb)
ds=DS(y1,eof)
new=predict.ds(ds,newdata=EOF(z2)
```

The point of using **common EOFs** is that the first is used for calibration and the second is used for prediction. You need to use `predict.ds(ds,newdata=TRUE)` to get appropriate results.
