### ISSUE TITLE
How to obtain combined EOF of two reanalysis fields?

### ISSUE THREAD

**Issue by javakh** [metno/esd#229]
Through common EOF we can obtain combined EOF of reanalysis and GCM. Can we apply same for obtaining combined EOF of two reanalysis fields ?
There was some function mixed.field in the old clim.pact package. How to implement this in new package?

Thanks.

**Comment by brasmus** [comment]
I think you must use `combine`to combine the fields first:

```r2
ceof <- EOF(combine(Reanalysis1,Reanalysis2))
```
