### ISSUE TITLE
Wrong date in NCEP/NCAR reanalysis?

### ISSUE THREAD

**Issue by brasmus** [metno/esd#23]
For some funny reason, I get different results in different situations... :-( Sometimes, the date associated with the NCEP/NCAR reanalysis looks ok, and sometimes I need to shift it with one year for a good compasison with ERA40:
t2mx <- retrieve('~/Desktop/air.mon.mean.nc',lon=c(-40,40),lat=c(40,75))
t2mx <- subset(t2mx,it=c(1958,2002))
T2mx <- as.4seasons(t2mx)
DJFx <- subset(T2mx,it=season)
eofx <- EOF(subset(DJFx,is=list(lon=range(lon(djf)),lat=range(lat(djf)))))
index(eofx) <- as.Date(paste(year(eofx) + 1,'-01-01',sep=''))

**Comment by abdelkaderm** [comment]
#####  Comparing temporal consistency in ERA40 with NCEP-NCAR 2m-temperature dataset

Try this ...

```r
t2m <- retrieve('~/data/ncep/air.mon.mean.nc',lon=c(-40,40),lat=c(40,75))
t2m <- subset(t2m,it=c(1958,2002))
T2mx <- as.4seasons(t2mx)
DJFx <- subset(T2mx,it=1)
era40 <- retrieve('~/data/ERA40/era40.t2m.nc',lon=c(-40,40),lat=c(40,75))
era40 <- subset(era40,it=c(1958,2002))
Era40 <- as.monthly(era40)
ERA40 <- as.4seasons(Era40)
djf <- subset(ERA40,it=1)
djfs <- as.station(spatial.avg.field(anomaly(djf)))
attr(djfs,"location") <- "ERA40"
DJFs <- as.station(spatial.avg.field(anomaly(DJFx)))
attr(DJFs,"location") <- "NCEP-NCAR"
com <- combine.stations(djfs,DJFs)
plot(com)
```
[https://github.com/metno/esd/blob/master/img/era40vsncep.png](https://github.com/metno/esd/blob/master/img/era40vsncep.png)
