### ISSUE TITLE
CCA proportions of variance?

### ISSUE THREAD

**Issue by puotila** [metno/esd#232]
Hi,

I enjoy using esd a lot, many thanks for your work! I have one issue and I wonder if you could provide me some advice.

I have not been able to figure out how to calculate the proportions of variance for canonical modes (see e.g eqs. 12.12 in  the Wilks book 2006 edition). I think that is important because even the mutual correlation of variates could be high, they might explain only a small portion of variability of input variables. Have you looked into this?

Petteri

**Comment by brasmus** [comment]
I think that @kajsamp has improved the CCA (Canonical correlation analysis) function recently.
