### ISSUE TITLE
Does esd work in the Jordan river basin location?

### ISSUE THREAD

**Issue by abeerhaddad** [metno/esd#236]
I want to statistically dowsncale data in the Jordan River Basin but 'esd' doesn't seem to work (lon (35-37) lat (32-33))
Thanks

**Comment by brasmus** [comment]
Can you provide the R-code and the data that you used?

**Comment by abdelkaderm** [comment]
Hi there, 

To add on top of Rasmus' question. Which time scale are you interested in? Daily, monthly, seasonal ?
