### ISSUE TITLE
CORDEX daily downscaling

### ISSUE THREAD

**Issue by dqc30** [metno/esd#237]
Hi! Does "esd" fully supports future daily downscaling? I know that the description says "The package contains R functions for retrieving data, making climate analysis and downscaling of monthly mean and **daily** mean global climate scenarios.", but I'm having some issues with its use, which I'll go further into if the package is supposed to support it. Thanks!

**Comment by abdelkaderm** [comment]
Well, up to now we have not implemented downscaling of the daily means. We are working on this and will probably be using weather generators conditioned on the daily large scale features to produce projections of daily means of temperature and precipitation. 

Bests,

**Comment by dqc30** [comment]
I see. Maybe that's why in check.ncdf4, around line 340, you force the index to be monthly and I ended up with dates until the year 6500.

**Comment by brasmus** [comment]
Yes but we do it the new smart way. Rather than downscaling weather, we
downscale climate. We define climate as statistical parameters describing
pdfs for daily or even sub-daily meteolological variables.

Den tor. 7. jun. 2018, 15:16 skrev dqc30 <notifications@github.com>:

**Comment by dqc30** [comment]
Sure, I think for this some kind of weather generator is needed. I'm currently looking for a suitable tool to do the work-around for getting daily projections, maybe a two step statistical downscaling. I'm interested analyzing the change in extreme events (return periods too), dry/wet days, shift of growing season and such, if possible, with the available tools and time to finish my master thesis. I really appreciate the efforts put in this package, is a very comprehensive tool.

**Comment by brasmus** [comment]
We are planning to include a more complete suite of weather generators, but we haven't got that far yet..

**Comment by brasmus** [comment]
@abdelkaderm will soon include a weather generator.
