### ISSUE TITLE
fail to install esd in R 

### ISSUE THREAD

**Issue by junliscut** [metno/esd#238]
l run the follwing code:
#library('devtools')
install_github('abdelkaderm/esd')# 

but it fail to install and the message is displayed as follows：
Error in parse(outFile) : 句法分析器22行里不能有多字节字符
ERROR: unable to collate and parse R files for package 'esd'
* removing 'C:/Users/user/Documents/R/win-library/3.5/esd' 
In R CMD INSTALL
Installation failed: Command failed (1)

**Comment by abdelkaderm** [comment]
Dear, 

Please try to use 
`install_github('metno/esd')`

Bests,
