### ISSUE TITLE
fail to install esd when l download the 'esd' zipped file from esd-on-figshare. 

### ISSUE THREAD

**Issue by Algernonthanks** [metno/esd#239]
l failed to install the esd packages from GitHub using R , so l try to install it from figshare. however, l still fail to install it.

when l run the code: install.packages("esd_1.0.tar.gz", "C:/Users/user/Documents/R/win-library/3.5",repos = NULL). The error message is displayed as follows:

236 ERROR: dependency 'ncdf' is not available for package 'esd'
* removing 'C:/Users/user/Documents/R/win-library/3.5/esd'
In R CMD INSTALL
Warning in install.packages :
  installation of package ‘esd_1.0.tar.gz’ had non-zero exit status

well, l hope you can help me to solve this  issue

**Comment by abdelkaderm** [comment]
Dear, 

The files on figshare are not up to date. It is recommended to install the package using 'devtools' R package instead.

Bests,

**Comment by abdelkaderm** [comment]
Try using rstudio for installing the package as it may solve some of the conflicts on Windows machines.

**Comment by junliscut** [comment]
so sad, l try to use the rstudio but l still failled. The errors showed in the following:

Downloading GitHub repo metno/esd@master
from URL https://api.github.com/repos/metno/esd/zipball/master
Installing esd
Installing 1 package: ncdf4
trying URL 'https://mirrors.tuna.tsinghua.edu.cn/CRAN/bin/windows/contrib/3.5/ncdf4_1.16.zip'
Content type 'application/zip' length 2597035 bytes (2.5 MB)
downloaded 2.5 MB

package ‘ncdf4’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\Administrator\AppData\Local\Temp\RtmpeKewQG\downloaded_packages
"D:/PROGRA~1/R/R-35~1.1/bin/x64/R" --no-site-file --no-environ --no-save  \
  --no-restore --quiet CMD INSTALL  \
  "C:/Users/Administrator/AppData/Local/Temp/RtmpeKewQG/devtools97cde85348/metno-esd-060035d"  \
  --library="D:/Program Files/R/R-3.5.1/library" --install-tests 

* installing *source* package 'esd' ...
** R
Error in parse(outFile) : a syntactic parser can not have a multi byte character in 23 lines
ERROR: unable to collate and parse R files for package 'esd'
* removing 'D:/Program Files/R/R-3.5.1/library/esd'
In R CMD INSTALL
Installation failed: Command failed (1)

**Comment by abdelkaderm** [comment]
This is wired. But you may have access permissions issues here to write on disc. Are you administrator of the machine?

**Comment by brasmus** [comment]
Try installing the packages 'zoo' and 'ncdf4' first. For 'ncdf4', you may need to install a library outside R (libnetcdf-dev for Linux). We have experienced some problems with this package on 64-bit Windows machines, but you can try with the 32-bit version.

**Comment by wenwenlithanks** [comment]
thank you for your great work. my machines was 64-bit Windows 10

**Comment by wenwenlithanks** [comment]
l try to install the package in RGui(32-bit). but l still faill. The error message is the same as above

**Comment by helene-b-e** [comment]
Since the error message has to do with parsing characters, could it be an idea to try changing the language settings? https://support.rstudio.com/hc/en-us/articles/200532197-Character-Encoding
