### ISSUE TITLE
I got errorError in if (match(freq.att, freq.data, nomatch = FALSE)) { :    argument is of length zero when i read File C:\Users\Admin\Documents\MATLAB\Main\CORDEX-Data\IITM\GFDL-ESM2M\historical\r1\IITM-RegCM4\v411\mon\pr\pr_WAS-44i_GFDL-ESM2M_historical_r1_IITM-RegCM4_v411_mon_195001-195012.nc (NC_FORMAT_CLASSIC):

### ISSUE THREAD

**Issue by Ganesh1605** [metno/esd#243]
I also traceback but i got 4: check.ncdf4(ncid, param = param, verbose = verbose)
3: retrieve.ncdf4(ncfile, path = path, param = param, verbose = verbose, 
       ...)
2: retrieve.default(ncfile = filename, param = "pr", lon = c(71.5, 
       74.5), lat = c(19.5, 22), plot = TRUE)
1: retrieve(ncfile = filename, param = "pr", lon = c(71.5, 74.5), 
       lat = c(19.5, 22), plot = TRUE)

**Comment by abdelkaderm** [comment]
Are you running the latest version. As far as I can see, this check has been excluded from retrieve function.

Bests,

**Comment by Ganesh1605** [comment]
yeaa i run latest version from github is it there any other latest version

**Comment by abdelkaderm** [comment]
I guess you are using a windows working station. Is that right ?

**Comment by Ganesh1605** [comment]
yeaa

**Comment by Ganesh1605** [comment]
i have ncdf4 also

**Comment by abdelkaderm** [comment]
then, it should be sth else. Can you run 

`summary.ncdf4(ncfilename)`

and send me the output ?
