### ISSUE TITLE
Error in installation in R3.6

### ISSUE THREAD

**Issue by njshippee** [metno/esd#248]
Hello, I'm getting an error message when trying to install ESD in DSensemble.R on line 1517. Details are here. Do you have any suggestions?

* installing *source* package 'esd' ...
** using staged installation
** R
Error in parse(outFile) : 
  C:/Users/nshippee/AppData/Local/Temp/RtmpY94tH5/R.INSTALLab0368961c6/esd/R/DSensemble.R:1517:25: unexpected symbol
1516:       plot((cal$x - mean(cal$x))/sd(cal$x),type='l',lwd=2,ylab='',xlab='',col=rgb(0.6,0.3,0))
1517:       axis(1,col='grey')X
                              ^
ERROR: unable to collate and parse R files for package 'esd'
* removing

**Comment by abdelkaderm** [comment]
Hi there, 

there was a typo in Line 1517. It should work now. :-)
