### ISSUE TITLE
esd installation failed

### ISSUE THREAD

**Issue by MeJitendra** [metno/esd#249]
> install_github('metno/esd')
Downloading GitHub repo metno/esd@master
   checking for file ‘/tmp/RtmpBPJeuV/remotes7178480c07a7/metno-esd-0c3a71b/DESC✔  checking for file ‘/tmp/RtmpBPJeuV/remotes7178480c07a7/metno-esd-0c3a71b/DESCRIPTION’
─  preparing ‘esd’:
✔  checking DESCRIPTION meta-information
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  looking to see if a ‘data/datalist’ file should be added
   Warning: file ‘py.script.rda’ has magic number 'RDX3'
     Use of save versions prior to 2 is deprecated
     unable to create a ‘datalist’ file: may need the package to be installed
─  building ‘esd_1.9.09.tar.gz’
   
Installing package into ‘/home/redfx/R/x86_64-pc-linux-gnu-library/3.4’
(as ‘lib’ is unspecified)
* installing *source* package ‘esd’ ...
** R
** data
** demo
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
Warning: file ‘py.script.rda’ has magic number 'RDX3'
  Use of save versions prior to 2 is deprecated
Error in load(zfile, envir = envir) : 
  bad restore file magic number (file may be corrupted) -- no data loaded
ERROR: installing package indices failed
* removing ‘/home/redfx/R/x86_64-pc-linux-gnu-library/3.4/esd’
Error: Failed to install 'esd' from GitHub:
  (converted from warning) installation of package ‘/tmp/RtmpBPJeuV/file71782913443e/esd_1.9.09.tar.gz’ had non-zero exit status

**Comment by brasmus** [comment]
Thanks for posting the issue. The problem should be fixed in the latest version: esd_1.9.10
