### ISSUE TITLE
How to regrid for multiple point locations if the longitude and latitude values are in a data frame.

### ISSUE THREAD

**Issue by MeJitendra** [metno/esd#252]
Dear Sir,
I have a data frame 'DT' having two columns and 1000 rows (locations) with Longitude in DT$Lon and Latitude in DT$Lat. 
Also I have a field object (ECMWF) which I want to use for regrid.

I have used the following code and it is taking 3 hours to regrid.  
```
data_interp<-list()
for(i in 1:1000){
data.interp[[i]]<-regrid(ECMWF,is=list(lon=DT$Lon[i], lat=DT$Lat[i]))
                      }
```
So, I modified the whole code to a single line as below. Which took 2 seconds to run.  
`data.interp<-regrid(ECMWF,is=list(lon=DT$Lon, lat=DT$Lat))`

But, this command has generated 1000*1000 (=1000000) columns. That means it used all possible combinations of Lat and Lon from the data frame. 

I want to regrid for the unique pair of Lat and Lon from the data frame. How to do that?

Warm Regards,
Jitendra

**Comment by abdelkaderm** [comment]
Hi Jitendra, your grid may not be regular that is why you got 1000000 columns of all possible combinations. You need to convert the ECMWF product from irregular to a regular grid before you use regrid from esd
