### ISSUE TITLE
Error in creating field object using as.field

### ISSUE THREAD

**Issue by monamidutta** [metno/esd#253]
Hi 
I wanna create field object using as. field. I have already used this command to make the field object using earlier version but when I update esd package recently, as.field is giving error. Even I tried the this command with already given example in as.field function, which is generating the same error:

data <- round(matrix(rnorm(20*12),20,12),2); colnames(data) <- month.abb
x <- data.frame(year=1981:2000,data)
X <- as.station.data.frame(x,loc="",param="noise",unit="none")

year <- sort(rep(1991:2000,12))
month <- rep(1:12,length(1991:2000))
n <-length(year)
lon <- seq(-30,40,by=5); nx <- length(lon)
lat <- seq(40,70,by=5); ny <- length(lat)

y <- matrix(rnorm(nx*ny*n),n,nx*ny)
index <- as.Date(paste(year,month,1,sep="-"))
Y <- as.field(y,index,lon,lat,param="noise",unit="none")
**Error in zoo(x = x, order.by = index) : 
  argument "index" is missing, with no default**

**Comment by monamidutta** [comment]
The issues with as.feild is persisting. Kindly help me through it.
@brasmus @abdelkaderm 

Error in UseMethod("as.field") : 
  no applicable method for 'as.field' applied to an object of class "c('matrix', 'array', 'double', 'numeric')"

**Comment by monamidutta** [comment]
Thank for your reply (@brasmus ) Rasmus Sir. I have mentioned the arguments but the error persists. I think its regarding some issues with the classes "matrix, array etc". I have tried the example of as.field that is given in esd.pdf. Same error is coming

Regards

**Comment by abdelkaderm** [comment]
Hi Monami, 

The example works fine when you specify the arguments as follows. Please not that there is a mistake in the example you sent that must be fixed. The error is in the line 
`y <- matrix(rnorm(nx*ny*n),n,nx*ny)`
Once this is fixed, you can generate the field as follows
`Y <- as.field(y,index= index,lon=lon,lat=lat,param="noise",unit="none")`

Bests,

**Comment by monamidutta** [comment]
Hello Abdelkader Sir
I have tried with this also, but I am seeing the same error.

> year <- sort(rep(1991:2000,12))
> month <- rep(1:12,length(1991:2000))
> n <-length(year)
> lon <- seq(-30,40,by=5); nx <- length(lon)
> lat <- seq(40,70,by=5); ny <- length(lat)
> # Time dimension should come first, space second.
> y <- matrix(rnorm(nx*ny*n),n,nx*ny)
> index <- as.Date(paste(year,month,1,sep="-"))
> Y <- as.field(y,index=index,lon=lon,lat=lat,param="noise",unit="none")
Error in UseMethod("as.field") : 
  no applicable method for 'as.field' applied to an object of class "c('matrix', 'array', 'double', 'numeric')"


Is there any chance of getting older version of esd before January/ February 2020..
Actually I was working with as.field before January/February and was working absolutely fine. Then I updated the esd version and now its showing this error.

Regards

**Comment by brasmus** [comment]
It works for me:
```r2
year <- sort(rep(1991:2000,12))
month <- rep(1:12,length(1991:2000))
n <-length(year)
lon <- seq(-30,40,by=5); nx <- length(lon)
lat <- seq(40,70,by=5); ny <- length(lat)
y <- matrix(rnorm(nx*ny*n),n,nx*ny)
index <- as.Date(paste(year,month,1,sep="-"))
Y <- as.field(y,index=index,lon=lon,lat=lat,param="noise",unit="none")
map(Y)
```
![image](https://user-images.githubusercontent.com/7392034/92233654-f6c54680-eeb0-11ea-93be-ece2e4841c73.png)

**Comment by brasmus** [comment]
Perhaps you have an old 'y' in memory - try `rm(list=ls(); gc(reset=TRUE)`.

**Comment by monamidutta** [comment]
Respected Rasmus Sir and Abdelkader Sir

Even after multiple attempts I was not able to fix or understand the problem that I have mentioned previously. The same error persisted

However, I would like to inform you that I was able to solve it another way. I used the following command and I got desired (previous) result.
data1 is a matrix of 30 row and 10325 column
dres <- zoo(t(data1),order.by=dates)
zzres <- as.field.zoo(dres,lon=lon,lat=lat,param = "AOD",unit="none")

Regards

**Comment by brasmus** [comment]
Do the previous lines work if you used `as.field.default' rather than `as.field'? I see that `as.field.matrix`is not oone of the methods, but we can easily include it in the next version. Thanks for bringing up this issue.

**Comment by monamidutta** [comment]
I wanted to inform you that the above issue (as.field) has been resolved in the latest version of "esd" package and now the command is working absolutely fine.

Thank you

**Comment by brasmus** [comment]
Thanks, Monami! I will close this threads then. All the best!
