### ISSUE TITLE
Unable to retrieve reanalysis data having multiple pressure levels

### ISSUE THREAD

**Issue by javakh** [metno/esd#257]
It seems there is some bug in retrieve function in the new version of esd. When trying to retrieve reanalysis data having multiple pressure levels, getting the following error:
**rea=retrieve('D:/SAIARD_course/shum.mon.mean.nc',lon=c(70,77.5),lat=c(17.5,25),lev=850)** 
[1] "Warning : Calendar attribute has not been found in the meta data and will be set automatically."
Error in Rsx_nc4_get_vara_double: NetCDF: Index exceeds dimension bound
Var: shum  Ndims: 4   Start: 0,28,26,28 Count: 820,4,4,4
Error in ncvar_get_inner(ncid2use, varid2use, nc$var[[li]]$missval, addOffset,  :
  C function R_nc4_get_vara_double returned error

But it's working fine reanalysis data without pressure level:
**rea=retrieve.ncdf4('D:/SAIARD_course/slp.mon.mean.nc', lon=c(70,77.5),lat=c(17.5,25) )**
[1] "Warning : Calendar attribute has not been found in the meta data and will be set automatically."

Please note that in previous versions of esd, I was able to retrieve data at various pressure levels

**Comment by brasmus** [comment]
Sorry for not having responded earlier here on this page. Is there still a problem?

**Comment by javakh** [comment]
Yes the problem persists in esd_1.9.52. Please resolve this issue.

*Javed Akhter, PhD*
*Formerly, Project Scientist-C, **IITM-Pune*
*Formerly, DST-INSPIRE fellow, Jadavpur University, Kolkata*

*Mob-+91-8981802238*

**Comment by brasmus** [comment]
Tat is a very old version. Try the latest 1.9.74. You may find it from  https://drive.google.com/drive/folders/1mUkpH50DFISWzL71I4eXO17eQ7_Vi2wu. 

I tried
```r2
> rea=retrieve('~/Downloads/shum.mon.mean.nc',lon=c(70,77.5),lat=c(17.5,25),lev=850)
[1] "Warning : Calendar attribute has not been found in the meta data and will be set automatically."
> map(rea)
```
with no problem. Also you should check your version of R. We have moved to the later releases (R.4.0.5)
