### ISSUE TITLE
Retrieving data from 150 E to 160 W from netCDF files.

### ISSUE THREAD

**Issue by javakh** [metno/esd#261]
Dear all,
I wish to know that how can I retrieve data from 150 E to 160 W.
If I use retrieve(.........,lon=c(150,-160)) [using negative for west], it is throwing an error.
If I use  retrieve(.........,lon=c(-150,160)), it is giving the region from 160W to 0 then 0 to 150E, the whole region, not the region I want to use.
Please suggest.

**Comment by brasmus** [comment]
Here is one way to do it: ```r
slp0 <- retrieve('~/Downloads/slp.mon.mean.nc')
lon(slp0)
slp0 <- g2dl(slp0)
lon(slp0)
slpx <- subset(slp0,is=list(lon=c(160,200),lat=c(-90,90)))
map(slpx)
```
![image](https://user-images.githubusercontent.com/7392034/152336076-61cea57d-6fb5-45ae-820f-8c8088b7b026.png)

**Comment by javakh** [comment]
Thank you so much for the solution. It is working.
