### ISSUE TITLE
using ESD for statistical processing

### ISSUE THREAD

**Issue by yuzee-333** [metno/esd#272]
Hey esd community.

My thesis is focusing on evaluating the ability of CMIP6 models in simulating sea surface temperature variations in the  South Atlantic Ocean and the consequent impacts on West African precipitation.
I must confess I am new to climate data analysis, as I'm more of a marine scientist but ocean-atmosphere interactions are of great interest to me.
Since I am conversant with coding in R and using Rstudio,  the 'esd' package will be very useful for my work, but I am having difficulty figuring out how to use it to carry out statistical processes such as detrending, standardizing, deseasoning, regression etc. For instance; I have done an EOF analysis of SST in the South Atlantic over a 40-year period (find results attached below) but I haven't figured out how to extract the time series from the eof analysis and normalize it. I have poured through the available documentation on the package, and it has helped a bit but I still can't find a solution to my problem.

Which functions in the package are relevant to the kind of work I want to do? 
and if not, are there other packages I can use?
[eof_example.pdf](https://github.com/metno/esd/files/10958625/eof_example.pdf)

**Comment by yuzee-333** [comment]
Thank you so much Abdelkadem
. 
I was able to plot the time series of the eof. 

![time_series_plot](https://user-images.githubusercontent.com/110180579/224833574-4e47a17e-7e6d-4034-89f5-bf28e36e7128.png)

However, is it possible to plot it like this ?, (with the standard deviations on the y-axis).

![image](https://user-images.githubusercontent.com/110180579/224833899-a40bfcf4-1b7a-42ae-be0a-4747ab5aa72c.png)

**Comment by abdelkaderm** [comment]
Hi, that is great !.
To produce the latest plot you would need to use some basic R functions I guess, Nevertheless, `spell` function may help a little but not sure if it will be fully appropriate, but you can try :)
