### ISSUE TITLE
DSensemble & PCA & several types of predictors

### ISSUE THREAD

**Issue by brasmus** [metno/esd#33]
Not finished? Not tested!

**Comment by brasmus** [comment]
DSensemble for multiple predictors.  Current: ```predictor="ERA40_pr_mon.nc"``` - set to a list or a vector of predictors?

**Comment by abdelkaderm** [comment]
I would use a list of predictors rather than a vector :+1:

**Comment by brasmus** [comment]
DSensemble.mu() uses a combination of three predictors as well as PCA for predictand. Not quite finished yet.

**Comment by brasmus** [comment]
DSensemble works for single element predictors and predictands: single stations, PCA, and EOF.
