### ISSUE TITLE
Graphics & infographics 

### ISSUE THREAD

**Issue by brasmus** [metno/esd#39]
Need to fill some of the methods with cool plots:
vis()
diagram()

**Comment by kajsamp** [comment]
I've added two scatterplot functions to vis.R. They are called binscatter.hex and binscatter.sunflower. Not sure about hte naming convention here. Should I rather call them vis.binscatter? 

Two examples:
![binscatter hex](https://cloud.githubusercontent.com/assets/10116084/6062631/8b0383c2-ad51-11e4-9b28-694c8a025934.png)
![binscatter sunflower](https://cloud.githubusercontent.com/assets/10116084/6062632/8eb1ab16-ad51-11e4-87f9-ecfa93d7c0b7.png)

**Comment by abdelkaderm** [comment]
Very nice, but on which results these functions will be applied ?

**Comment by kajsamp** [comment]
They are applied to any 2 vectors of the same length. Maybe two station objects, but then we would have to add a few lines to match up the dates. Also I was thinking of adapting them to show the storm density on a map.

**Comment by kajsamp** [comment]
I've added vis.trends which plots trends for multiple time periods. The function should work for any zoo object. It's pretty slow when handling long time series but I think the code can be made more efficient, replacing loops with apply/aggregate. 

An example:
```r
data(Oslo)
vis.trends(Oslo,unitlabel="oC",varlabel="T2m")
```
![vis trends](https://cloud.githubusercontent.com/assets/10116084/6126524/ce353612-b121-11e4-85f1-578f25b9bd0f.png)

**Comment by abdelkaderm** [comment]
`vis.trend` has been recently updated. The plot has been improved and looks different from the example given above
