### ISSUE TITLE
colour palette and arguments for map

### ISSUE THREAD

**Issue by brasmus** [metno/esd#40]
Consolidate the use of arguments in map.field and map.station. New palettes from seNorge have been added to colscal, but it does not yet work for the maps. Also, the colour bare often is shown without the values expressed in numbers.

**Comment by abdelkaderm** [comment]
The values must show up. I think the problem comes from redefining the figure zone using par(). I think it works for single figure and not composite one !

**Comment by kajsamp** [comment]
I have added the built in palettes to colscal (rainbow, gray.colors, etc. See picture: http://zoonek2.free.fr/UNIX/48_R/g327.png). I see no reason to define our own rainbow when one is available.

**Comment by abdelkaderm** [comment]
It is better to have a predefined color scale ! I was not happy with the existing ones.

**Comment by kajsamp** [comment]
Do you mean that we should not use the built in palettes? I think the ones that you have defined in colscal are good for many purposes but we need more options. For example, now I am in need of a color scale that is equally strong and clear in all parts, i.e., that does not have a white/pale region.

**Comment by abdelkaderm** [comment]
No, I did not mean that. We should keep it as flexible as possible with the possibility to use or not the built-in palettes or the predefined esd color scales. both options are welcome :+1:

**Comment by brasmus** [comment]
Now, the palettes are not working and map() crashes...

**Comment by brasmus** [comment]
I think I managed to fix this.

**Comment by abdelkaderm** [comment]
`map` is working fine again and several bugs have been fixed regarding the colour bar. :+1:
