### ISSUE TITLE
subset() not working with both is and it arguments at the same time

### ISSUE THREAD

**Issue by OskarMETNO** [metno/esd#41]
Previously this worked (from paper55.R):
`T2m.era40 <- subset(T2m.era40,it=it, is=is)`
Now I get the following message:
`Error in rval[i, j, drop = drop., ...] : invalid subscript type 'list'`
(My 'is' object is a list, but I think this is how it should be.)

subset() works with the 'is' and 'it' arguments separately in sequence, like this:
```
T2m.era40 <- subset(T2m.era40,it=it)
T2m.era40 <- subset(T2m.era40,is=is)
```
but not with both at the same time.

**Comment by brasmus** [comment]
I think it should work after my last changes:

```r2
it=c(1960,1980)
is <- list(lon=c(-40,30),lat=c(50,70))
T2m.era40 <- t2m.ERA40()
y <- subset(T2m.era40,it=it,is=is,verbose=TRUE)
map(y)
plot(y)
```
