### ISSUE TITLE
Unable to subset using index

### ISSUE THREAD

**Issue by javakh** [metno/esd#47]
I'm trying to subset with the following example data given in ESD package:

t2m <- t2m.NCEP(lon=c(-10,30),lat=c(50,70)) 
cal <- subset(t2m,it=c("1948-01-01","1980-12-01")) 

But i'm getting error message:

"Error in index(y) : object 'y' not found"

What is wrong here and how to overcome this?????

actually I need to subset index wise.

**Comment by abdelkaderm** [comment]
I did not get any error, please reinstall the latest **esd** version and try again,

```r
t2m <- t2m.NCEP(lon=c(-10,30),lat=c(50,70))
cal <- subset(t2m,it=c("1948-01-01","1980-12-01")) 
```
Use the function `range()` to get the range of dates form `cal` object as 
```r
range(time(cal))
```
This will produce the following which corresponds to your request in `it`
> [1] "1948-01-01" "1980-12-01"
