### ISSUE TITLE
unable to install esd-0.9-3.zip in windows7 (64 bit)

### ISSUE THREAD

**Issue by javakh** [metno/esd#48]
while trying to install esd-0.9-3.zip in windows7 (64 bit) following error is showing.......

Error in read.dcf(file.path(pkgname, "DESCRIPTION"), c("Package", "Type")) : 
  cannot open the connection
In addition: Warning message:
In read.dcf(file.path(pkgname, "DESCRIPTION"), c("Package", "Type")) :
  cannot open compressed file 'esd_0.9/DESCRIPTION', probable reason 'No such file or directory'

how to fix this???????

**Comment by brasmus** [comment]
Try again - check that there is sufficient space on your disc. Try installing with the 'devtools' package - install_github('metno/esd'). Try loading the esd-package from figshare: http://figshare.com/articles/esd_for_windows/1160494

**Comment by javakh** [comment]
I have sufficient disk space.I have installed this package in Ubuntu but
unable to install in windows.
