### ISSUE TITLE
DS

### ISSUE THREAD

**Issue by brasmus** [metno/esd#50]
Check the calibration of the model and the plot of the time series when there are missing data. The following code produced the graphics:
```r2
data(Oslo)
era40 <- t2m.ERA40(lon=c(-10,20),lat=c(55,65))
y <- subset(Oslo,it='jan')
X <- EOF(subset(era40,it='jan'))
ds <- DS(y,X)
plot(ds) # Looks OK
# Now we replace some values of y with missing data:
y2 <- y
set2na <- order(rnorm(length(y)))[1:50]
y2[set2na] <- NA
ds2 <- DS(y2,X)
plot(ds2) # Not OK
```

![screenshot from 2015-03-05 10 15 35](https://cloud.githubusercontent.com/assets/7392034/6502103/9b9112a6-c320-11e4-9049-7bc52f76b85b.png)
![screenshot from 2015-03-05 10 15 14](https://cloud.githubusercontent.com/assets/7392034/6502106/9ca30d02-c320-11e4-9d21-2dd4796b3bd3.png)

**Comment by abdelkaderm** [comment]
Hi Monami, 

> 1. There is some problem regarding DS for NA values. Its not working well if the station data contains missing values. Work for IMD gridded DS. DS(stn,EOF(IMD_gridded))

Yes, you are right, we have identified this problem. Rasmus will try to fix this as soon as possible. But remember that if you have huge gaps in the calibration period, the regression will fail !

**Comment by brasmus** [comment]
Fixed
