### ISSUE TITLE
ds.pca

### ISSUE THREAD

**Issue by abdelkaderm** [metno/esd#54]
From Jitendra, 

Hello Sir,
I am facing problem with the 'ds.pca' function. The problem is mentioned below
> ds.pca = DS.pca(pca,,rean1)
y=            mon=          m=            verbose=      
X=            method=       eofs=         weighted=     
biascorrect=  swsm=         rmtrend=      ...=          
> ds.pca = DS.pca(pca,rean1,threshold=1)
Error in coredata(x) > threshold : 'threshold' is missing

**Comment by brasmus** [comment]
Check out the example provided in the man pages: 

```r2
# Example for using PCA in downscaling
## nacd <- station(src='nacd')
## X <- annual(nacd)
X <- station(src='nacd')
nv <- function(x) sum(is.finite(x))
ok <- (1:dim(X)[2])[apply(X,2,nv) == dim(X)[1]]
X <- subset(X,is=ok)
pca <- PCA(X)
map(pca)

slp <- slp.NCEP(lon=c(-20,30),lat=c(30,70))
eof <- EOF(slp,it=1)
ds <- DS(pca,eof)
# ds is a PCA-object
plot(ds)
```
