### ISSUE TITLE
floor and celling !

### ISSUE THREAD

**Issue by abdelkaderm** [metno/esd#57]
Monami said : 
> 3. “Floor(min(lon.new)-2, celling(max(lon.new)+2, can you say why +2 and -2? or what is the exact meaning by this in term of mathematics?

From R documentation 
```r 
‘ceiling’ takes a single numeric argument ‘x’ and returns a
numeric vector containing the smallest integers not less than the
corresponding elements of ‘x’.

‘floor’ takes a single numeric argument ‘x’ and returns a numeric
vector containing the largest integers not greater than the
corresponding elements of ‘x’.
```
be careful, it is called "ceiling" and not "celling". Also, the +-2 is only used to ensure a kind of range values.

**Comment by javakh** [comment]
But why +-2 ,not +-1 or +-0.5 or so on.......??????

**Comment by abdelkaderm** [comment]
It is an arbitrary choice ! 

This is only used to avoid miscalculations at the boundaries of the chosen domain.
