### ISSUE TITLE
Adding trend line in plot.type='multiple'

### ISSUE THREAD

**Issue by MeJitendra** [metno/esd#58]
Dear sir,
How would i add a linear or lowess 
![screenshot from 2015-03-14 17 10 43](https://cloud.githubusercontent.com/assets/11473497/6651581/cf69a676-ca3f-11e4-99aa-614a9772f688.png)
trend line to each of the plot in ESD, plot.type='multiple' as shown in the figure

**Comment by abdelkaderm** [comment]
I will think about it, not sure to have a quick solution for that ....

**Comment by MeJitendra** [comment]
Ok sir.
