### ISSUE TITLE
Adding country or state boarder to a PCA plot in ESD

### ISSUE THREAD

**Issue by MeJitendra** [metno/esd#59]
Dear Sir,
Using the Command like
plot(PCA(X)) Produces following figure
![screenshot from 2015-03-14 17 23 30](https://cloud.githubusercontent.com/assets/11473497/6651601/d97a4da4-ca40-11e4-9c6a-ab688643a455.png)
How would i add a country border to each of the EOF map and the climatology to the above maps like the following figures
![screenshot from 2015-03-14 17 36 17](https://cloud.githubusercontent.com/assets/11473497/6651624/9e795770-ca42-11e4-865c-22e6131306ae.png)

**Comment by brasmus** [comment]
We plan to write a new routine for plot.pca - the current routine will be called vis.pca.

**Comment by abdelkaderm** [comment]
Hi Jitendra, 

Please reinstall the package and use plot again ... it will produce a different plot but the country borders are there.
![plot_pca_precip_imd](https://cloud.githubusercontent.com/assets/6603481/8372488/150d9d22-1be4-11e5-8312-014346aeedd9.jpg)

**Comment by MeJitendra** [comment]
Thank you sir. This looks good now.
