### ISSUE TITLE
wiki errors

### ISSUE THREAD

**Issue by kajsamp** [metno/esd#60]
I'm going through the esd wiki. On the page about data handling (https://github.com/metno/esd/wiki/2.-Data-handling), there is a figure of the mean temperature in Oslo, produced using this code:

```r
t2m.mon <- station.metnom(stid="18700",param="t2m")
t2m.ann <- as.annual(t2m.mon, FUN = "mean")
plot(t2m.ann)
```

When I try to reproduce the plot I get huge errorbars, not at all like the figure at the wiki page.

**Comment by abdelkaderm** [comment]
We have recently added an extra argument called `errorbar=FALSE` showing error bars based on 2 * Std of the observations.
You can try
```r
t2m.mon <- station.metnom(stid="18700",param="t2m")
t2m.ann <- as.annual(t2m.mon, FUN = "mean")
plot(t2m.ann,errorbar=FALSE)
```

**Comment by kajsamp** [comment]
Well that gives me a figure without errorbars. Did you calculate the error bars differently before, not as 2*std of the observations? Is that why I can't reproduce the example?

**Comment by abdelkaderm** [comment]
Need to have a look at it, will come to you later on !

**Comment by abdelkaderm** [comment]
So, there was a mistake in the line 
```r
t2m.ann <- as.annual(t2m.mon, FUN = "mean")
```
that has to be replaced by 
```r
t2m.ann <- as.annual(t2m.dly, FUN = "mean",ylim=c(2,10))
```
The error bar in the figure corresponds to those obtained from daily and not monthly values. I have updated the page accordingly :+1:
