### ISSUE TITLE
Regarding replacement of missing values in station with grided data

### ISSUE THREAD

**Issue by monamidutta** [metno/esd#61]
for(i in 1:ncol(sixteen_station)){ 
stn1 <- subset(sixteen_station,is=i) 
jan <- subset(stn1,it='jan') 
z1 <- subset(Z,is=list(lon=c(72,80),lat=c(33,37))) # Z is  gridded data(1 x 1), this domain is showing best pattern for jan month.
eof <- EOF(subset(z1,it='jan')) 
ds <- DS(jan,eof) 
plot(ds) 

After running this code at some stations the down scaling time series shows a straight line. Even if we increase the domain the problem persist. Problem doesn't solve with erat2m data also.

**Comment by kajsamp** [comment]
Hi Monami, 

I see that this issue was posted quite a long time ago. Did you solve the problem? I tried reproducing the example with temperature data from Norway but for me the downscaling worked perfectly fine.

Best, Kajsa

**Comment by brasmus** [comment]
Try using pcafill()
