### ISSUE TITLE
problem: install_github('metno/esd') - command failed

### ISSUE THREAD

**Issue by MaSp2** [metno/esd#70]
Hey! I am a newbie in R.
I tried to install esd with >install_github('metno/esd')
this error is showing up: 
* installing *source* package 'esd' ...
** R
** data
** demo
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
Warnung in readLines(file) :
  unvollständige letzte Zeile in './demo/00Index' gefunden
** testing if installed package can be loaded
*** arch - i386
Error : package 'ncdf4' is not installed for 'arch = i386'
Fehler: Laden fehlgeschlagen
Ausführung angehalten
*** arch - x64
ERROR: loading failed for 'i386'

The R version is 3.1.3, and ncdf4_1.12
Is there maybe an easy solution?? Thank you

**Comment by abdelkaderm** [comment]
Which operating system are you using ?

**Comment by MaSp2** [comment]
I use windows 7, 64
'zoo', 'devtools' and 'ncdf4' are installed

**Comment by abdelkaderm** [comment]
What is you the platform on wich R is installed.
Is it 64 or 32 bits
please open an R session and copy and send me the first three lines.
like 
> R version 3.0.3 (2014-03-06) -- "Warm Puppy"
Copyright (C) 2014 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

because you got this error message, 
>
arch - i386 Error : package 'ncdf4' is not installed for 'arch = i386' Fehler: Laden fehlgeschlagen Ausführung angehalten *** arch - x64 ERROR: loading failed for 'i386'

and seems like there is a conflict between you windows system x64 and i386

**Comment by MaSp2** [comment]
Ah I see! 
The first lines are:
R version 3.1.3 (2015-03-09) -- "Smooth Sidewalk"
Copyright (C) 2015 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)

**Comment by abdelkaderm** [comment]
Have you installed ncdf4 32 or 64 bits ?

**Comment by MaSp2** [comment]
I installed the 64 bit version from http://cirrus.ucsd.edu/~pierce/ncdf/  (ncdf4_1.12.zip)

**Comment by abdelkaderm** [comment]
First, try with ncdf4 32 bits instead. 

If it is still not installing, you may try to install the ncdf4 from cran using 
```r
install.packages("ncdf4") 
```
or download and install from http://cran.r-project.org/web/packages/ncdf4/index.html

**Comment by MaSp2** [comment]
installing the 32 bits version results in: 
Error: Package ‘ncdf4’ is for 'arch=x64' not installed

from cran it results in:    
package ‘ncdf4’ is available as a source package but not as a binary

Warning in install.packages :
  package ‘ncdf4’ is not available (as a binary package for R version 3.1.3)

Installing the package source 'ncdf4_1.13.tar.gz ' from cran.r-project is only working if converted into a .zip file. But even then when loading (library('ncdf4')) then it results in: 
Error in library("ncdf4") : 
  ‘ncdf4’ is not a valid installed package

**Comment by abdelkaderm** [comment]
The package you installed through the website http://cirrus.ucsd.edu/~pierce/ncdf/ has been manipulated and may contain some errors. I will think about a temporary solution to overcome this problem by using the library `ncdf` instead of `ncdf4`. Will come to you back !

**Comment by abdelkaderm** [comment]
Try installing a previous version from figshare  http://figshare.com/authors/Rasmus_Benestad/530698
and see if the ncdf4 is still a problem.
>
From figshare,
First, download the 'esd' zipped file which corresponds to your operating system (Linux, Mac, or Windows) following this link esd-on-figshare. Then, download the zipped file from the esd repository on your local machine, and and install the package.

**Comment by MaSp2** [comment]
ok, i downloaded esd_0.9_3.zip from figshare
 >install_github('metno/esd')
results in
Downloading github repo metno/esd@master
Error in function (type, msg, asError = TRUE)  : 
  SSL read: error:00000000:lib(0):func(0):reason(0), errno 10054

**Comment by abdelkaderm** [comment]
You cannot use install_github any more in this case, you need to select "install package from zip file" item, then specify the zipped file that has been downloaded from figshare ...

**Comment by MaSp2** [comment]
this is producing
Warning in install.packages :
  cannot open compressed file 'esd_0.9/DESCRIPTION', probable reason 'No such file or directory'
Error in install.packages : cannot open the connection

**Comment by abdelkaderm** [comment]
I will try to have a look next week on how to proceed ... Sorry for this inconvenience ...

**Comment by MaSp2** [comment]
ok, thank you so far for your help!

**Comment by abdelkaderm** [comment]
Hi, I have removed all the dependencies to ncdf4 and we are now using ncdf instead as a temporary solution. This will not affect the outputs when using the package. Please reinstall the package again using the command
```r
install_github("metno/esd")
```
I have tried the installation on a windows server 2008 R2 Entreprise system and seems to work. I hope it will work on a Windows 7 

```r
Downloading github repo metno/esd@master
Installing esd
"C:/R-3.1.3/bin/x64/R" --vanilla CMD INSTALL  \
  "C:/Users/abdelkaderm/AppData/Local/Temp/5/RtmpUzAj0z/devtools1b7c466865c0/metno-esd-27394ce"  \
  --library="C:/R-3.1.3/library" --install-tests 

* installing *source* package 'esd' ...
** R
** data
** demo
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
Warning in readLines(file) :
  incomplete final line found on './demo/00Index'
** testing if installed package can be loaded
*** arch - i386
*** arch - x64
* DONE (esd)

```

**Comment by MaSp2** [comment]
Thanks a lot, it is working now!

**Comment by Mareke-76** [comment]
I am trying to install esd package on window 10, r version 4.0.5. But I am getting this, Downloading GitHub repo metno/esd@HEAD
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  download from 'https://api.github.com/repos/metno/esd/tarball/HEAD' failed
