### ISSUE TITLE
correlation map

### ISSUE THREAD

**Issue by MaSp2** [metno/esd#72]
I have a correlation matrix and would like to visualize it. 
I use corrplot(), but since there are not many significant correlations I need to fit the range of the displayed correlations (-0.5 to 0.5 for example). Additionally I would like to add a layer of countryborders (shp file). 
I saw a map like that on a poster on a conference introducing the esd package. Can you please provide me with the commands?

**Comment by abdelkaderm** [comment]
you can use the S3 method `map` to produce a correlation map with country borders as

```r
map(X)
```
where `X` is your correlation matrix. Be careful of longitudes and latitudes, when you produce the map, your matrix must be organized as (lon,lat)

**Comment by brasmus** [comment]
use corfield?
