### ISSUE TITLE
map.station and trends

### ISSUE THREAD

**Issue by brasmus** [metno/esd#73]
Mapping trends gives inconsistent results with different colour scales:
```r2
## The first plot:
map(Mu,FUN='trend',xlim=c(5,30),ylim=c(58,71),cex=2,col='grey',
        colbar=list(col=colscal(col='t2m'),breaks=seq(-0.4,0.5,by=0.05)))

# The secondd plot: more NAs are introduced with wider range for breaks - why?
map(Mu,FUN='trend',xlim=c(5,30),ylim=c(58,71),cex=2,col='grey',
        colbar=list(col=colscal(col='t2m'),breaks=seq(-0.5,0.5,by=0.05)))

```
 
![screenshot from 2015-04-08 14 11 08](https://cloud.githubusercontent.com/assets/7392034/7044958/392edae6-ddf9-11e4-83d9-c333c5d5ce45.png)
![mu trend norway](https://cloud.githubusercontent.com/assets/7392034/7044961/402c8046-ddf9-11e4-957b-4bfb3d2a9990.png)

**Comment by abdelkaderm** [comment]
ok, I will have a look !

**Comment by abdelkaderm** [comment]
Fixed now ! Try again
