### ISSUE TITLE
problem in interpolating GCM data in station location

### ISSUE THREAD

**Issue by javakh** [metno/esd#74]
I have taken a GCM file in the domain lon=c(71,85),lat=c(4,20) and trying to interpolate to following station locations using 'regrid' function and also using 'subset.station' function
station name lattitude longitude 
PUNALUR	9.00	    76.92
THRISSUR	10.52   76.22
SHIMOGA	13.93    75.63
HASSAN		13.00    76.15

But after interpolation I'm getting 'NA' values for these particular stations.

What is the reason and what is the solution of this problem??????

Waiting for your reply.

![r](https://cloud.githubusercontent.com/assets/11016843/7104709/24d0e88a-e111-11e4-82c0-9fed4d606166.jpg)

**Comment by abdelkaderm** [comment]
I did not understand your table. What are the column names ... are they stations .... remember that you have to create a `station` object based on your data before using `regrid` on stations.
```
# have you converted your matrix into a station object first ...
as.station(x=data, ....)
#

**Comment by javakh** [comment]
Yeah........each column represent  one station. Among 40 stations 5-6 stations( I have mentioned in previous post) are producing NA values.

**Comment by abdelkaderm** [comment]
I do not know why it is not working for only few stations. Please check the stations' coordinates that are correct. i.e. longitude and latitude !!!

**Comment by javakh** [comment]
The co-ordinates are correct and they are within the selected domain of GCM. I have given the co-ordinates in the first post. You may kindly check them.

**Comment by abdelkaderm** [comment]
Can you upload here the result of `str` applied to your station object and the syntax that you have used. Thanx !

**Comment by javakh** [comment]
Syntax:
latlon_spi<-read.table('/media/tutul/JAV/work-mar2015/latlon_spi.txt',header=T,sep='')
obj<-latlon_spi
setwd('/media/tutul/B0BEA327BEA2E556/Research/ar5-past-pr')
filelist<-list.files(pattern="*.nc")
ar5_full<-lapply(FUN="retrieve.ncdf4",filelist,lon=c(71,85),lat=c(6,16),time=c(1961,2005))
gcm<-list()
ar5_pr_spi<-list()
for(i in 1:length(ar5_full)){
             gcm[[i]]<-ar5_full[[i]]
gcm[[i]]=gcm[[i]]*30
s=attr(gcm[[i]],"model_id")
print(s)
df<-NULL
for(j in 1:nrow(obj)){
       station<-obj[j,1]
       lati<-obj[j,2]
       long<-obj[j,3]
   reg<-suppressWarnings(regrid(gcm[[i]],is=list(longitude=long,latitude=lati)))
print('########')

if(j==1){
df<-reg
}
else {
df<-cbind(df,reg)
}
}
ar5_pr_spi[[i]]<-df
}

![r1](https://cloud.githubusercontent.com/assets/11016843/7129186/69b09e5e-e27a-11e4-9f33-a7befa6b0d6f.jpg)

**Comment by javakh** [comment]
I suppose there is a bug in regrid function.I'm giving a example below-
> str(gcm3)
‘zoo’ series from 1961-01-01 to 2005-12-01
  Data: num [1:540, 1:144] 26.4 30.3 26.3 24.7 90.8 ...
 - attr(*, "variable")= chr "pr"
 - attr(*, "longname")= chr "Precipitation"
 - attr(*, "units")= chr "mm/day"
 - attr(*, "dimensions")= int [1:3] 12 12 540
 - attr(*, "longitude")= num [1:12(1d)] 67.5 70.3 73.1 75.9 78.8 ...
 - attr(*, "greenwich")= logi FALSE
 - attr(*, "latitude")= num [1:12(1d)] 6.98 9.77 12.56 15.35 18.14 ...
 - attr(*, "calendar")= chr "standard"
 - attr(*, "file")= chr "pr_Amon_bcc-csm1-1_historical_r1i1p1_185001-201212.nc"
 - attr(*, "title")= chr "bcc-csm1-1 model output prepared for CMIP5 historical"
 - attr(*, "source")= chr "bcc-csm1-1"
 - attr(*, "model_id")= chr "bcc-csm1-1"
 - attr(*, "experiment_id")= chr "output"
 - attr(*, "realization")= int 1
 - attr(*, "timeunit")= chr "month"
 - attr(*, "type")= chr "model"
 - attr(*, "URL")= chr "http://climexp.knmi.nl/"
 - attr(*, "call")= language FUN(ncfile = c("pr_Amon_ACCESS1-0_historical_r1i1p1_185001-200512.nc",  "pr_Amon_ACCESS1-3_historical_r1i1p1_185001-200512.nc", "pr_Amon_bcc-csm1-1_historical_r1i1p1_185001-201212.nc",  ...
 - attr(*, "institution")= logi NA
 - attr(*, "reference")= logi NA
 - attr(*, "history")=List of 3
  ..$ call       : language FUN(c("pr_Amon_ACCESS1-0_historical_r1i1p1_185001-200512.nc", "pr_Amon_ACCESS1-3_historical_r1i1p1_185001-200512.nc",  "pr_Amon_bcc-csm1-1_historical_r1i1p1_185001-201212.nc", "pr_Amon_bcc-csm1-1-m_historical_r1i1p1_185001-201212.nc",  ...
  ..$ timestamp  : chr "Sat Apr 18 07:17:24 2015"
  ..$ sessioninfo:List of 3
  .. ..$ R.version  : chr "R version 3.0.2 (2013-09-25)"
  .. ..$ esd.version: chr "esd_0.9-3"
  .. ..$ platform   : chr "x86_64-pc-linux-gnu (64-bit)"
  Index:  Date[1:540], format: "1961-01-01" "1961-02-01" "1961-03-01" "1961-04-01" ...
> reg3<-regrid(gcm3,is=list(lon=78.83,lat=14.48))
Warning message:
In min(diff(xo)) : no non-missing arguments to min; returning Inf
> str(reg3)
‘zoo’ series from 1961-01-01 to 2005-12-01
  Data: num [1:540, 1] NA NA NA NA NA NA NA NA NA NA ...
 - attr(*, "longitude")= num 78.8
 - attr(*, "latitude")= num 14.5
 - attr(*, "variable")= chr "pr"
 - attr(*, "longname")= chr "Precipitation"
 - attr(*, "units")= chr "mm/day"
 - attr(*, "greenwich")= logi FALSE
 - attr(*, "calendar")= chr "standard"
 - attr(*, "file")= chr "pr_Amon_bcc-csm1-1_historical_r1i1p1_185001-201212.nc"
 - attr(*, "title")= chr "bcc-csm1-1 model output prepared for CMIP5 historical"
 - attr(*, "source")= chr "bcc-csm1-1"
 - attr(*, "model_id")= chr "bcc-csm1-1"
 - attr(*, "experiment_id")= chr "output"
 - attr(*, "realization")= int 1
 - attr(*, "timeunit")= chr "month"
 - attr(*, "type")= chr "model"
 - attr(*, "URL")= chr "http://climexp.knmi.nl/"
 - attr(*, "call")= language FUN(ncfile = c("pr_Amon_ACCESS1-0_historical_r1i1p1_185001-200512.nc",  "pr_Amon_ACCESS1-3_historical_r1i1p1_185001-200512.nc", "pr_Amon_bcc-csm1-1_historical_r1i1p1_185001-201212.nc",  ...
 - attr(*, "institution")= logi NA
 - attr(*, "reference")= logi NA
 - attr(*, "history")=List of 3
  ..$ call     :List of 4
  .. ..$ : language regrid.field(gcm3, is = list(lon = 78.83, lat = 14.48))
  .. ..$ : language subset.field(x, is = list(lon = c(floor(min(lon.new)) - 2, ceiling(max(lon.new)) +      2), lat = c(floor(min(lat.new)) - 2, ceiling(max(lat.new)) + 2)))
  .. ..$ : language g2dl.field(x, greenwich = FALSE)
  .. ..$ : language FUN(c("pr_Amon_ACCESS1-0_historical_r1i1p1_185001-200512.nc", "pr_Amon_ACCESS1-3_historical_r1i1p1_185001-200512.nc",  "pr_Amon_bcc-csm1-1_historical_r1i1p1_185001-201212.nc", "pr_Amon_bcc-csm1-1-m_historical_r1i1p1_185001-201212.nc",  ...
  ..$ timestamp: chr [1:4] "Mon Apr 20 11:16:18 2015" "Mon Apr 20 11:16:18 2015" "Mon Apr 20 11:16:18 2015" "Sat Apr 18 07:17:24 2015"
  ..$ session  :List of 3
  .. ..$ R.version  : chr "R version 3.1.1 (2014-07-10)"
  .. ..$ esd.version: chr "esd_0.4-1"
  .. ..$ platform   : chr "x86_64-w64-mingw32/x64 (64-bit)"
 - attr(*, "dimensions")= int [1:3] 1 1 540
  Index:  Date[1:540], format: "1961-01-01" "1961-02-01" "1961-03-01" "1961-04-01" ...
>

**Comment by javakh** [comment]
I suppose there is a bug in regrid function. I'm giving an example below----
> reg3<-regrid(gcm3,is=list(lon=78.83,lat=14.48))
Warning message:
In min(diff(xo)) : no non-missing arguments to min; returning Inf
> str(reg3)
‘zoo’ series from 1961-01-01 to 2005-12-01
  Data: num [1:540, 1] NA NA NA NA NA NA NA NA NA NA ...
 - attr(*, "longitude")= num 78.8
 - attr(*, "latitude")= num 14.5

**Comment by abdelkaderm** [comment]
I have run the following example and did not get any errors or warnings !
**Are you running the latest esd version ?**
Please try it and let me know whether you still have problems.

**Step1**. download the ACCESS1-0 historical from http://climexp.knmi.nl/selectmember.cgi?id=someone@somewhere&i=0&field=cmip5_tas_Amon_ACCESS1-0_historical into my /disk1/downloads/ folder  (*you can skip this step as you already have ncdf files downloaded** I have put this step to run exactly the same example)

**step2**. use retrieve to get a subset of the field as in your example 

```r
gcm <- retrieve(ncfile="/disk1/downloads/tas_Amon_ACCESS1-0_historical_000.nc",lon=c(71,85),lat=c(6,16),time=c(1961,2005))
```

**step3**. regrid as 

```r
reg <-regrid(gcm, is=list(lon=78.83,lat=14.48))
```
**step4**. Finally, display `str` 
```r
str(reg)
```
‘zoo’ series from 1961-01-01 to 2005-12-01
  Data: num [1:540, 1] 23.9 26.3 29.3 31.4 31.8 ...
 - attr(*, "variable")= chr "tas"
 - attr(*, "longname")= chr "Near-Surface Air Temperature"
 - attr(*, "units")= chr "degC"
 - attr(*, "longitude")= num 78.8
 - attr(*, "greenwich")= logi FALSE
 - attr(*, "latitude")= num 14.5
 - attr(*, "calendar")= chr "proleptic_gregorian"
 - attr(*, "file")= chr "/disk1/downloads/tas_Amon_ACCESS1-0_historical_000.nc"
 - attr(*, "title")= chr "ACCESS1-0 model output prepared for CMIP5 historical"
 - attr(*, "source")= chr "ACCESS1-0"
 - attr(*, "model_id")= chr "ACCESS1-0"
 - attr(*, "experiment_id")= chr "output"
 - attr(*, "realization")= int 1
 - attr(*, "timeunit")= chr "month"
 - attr(*, "type")= chr "model"
 - attr(*, "URL")= chr "http://climexp.knmi.nl/"
 - attr(*, "call")= language retrieve.ncdf4(ncfile = ncfile, param = "auto", lon = ..1, lat = ..2, time = ..3)
 - attr(*, "institution")= logi NA
 - attr(*, "reference")= logi NA
 - attr(*, "history")=List of 3
  ..$ call     :List of 4
  .. ..$ : language regrid.field(gcm, is = list(lon = 78.83, lat = 14.48))
  .. ..$ : language subset.field(x, is = list(lon = c(floor(min(lon.new)) - 2, ceiling(max(lon.new)) +      2), lat = c(floor(min(lat.new)) - 2, ceiling(max(lat.new)) + 2)))
  .. ..$ : language g2dl.field(x, greenwich = FALSE)
  .. ..$ : language retrieve.ncdf4(ncfile, param = "auto", ...)
  ..$ timestamp: chr [1:4] "Mon Apr 20 15:03:17 2015" "Mon Apr 20 15:03:17 2015" "Mon Apr 20 15:03:17 2015" "Mon Apr 20 15:02:06 2015"
  ..$ session  :List of 3
  .. ..$ R.version  : chr "R version 3.0.3 (2014-03-06)"
  .. ..$ esd.version: chr "esd_0.9-5"
  .. ..$ platform   : chr "x86_64-pc-linux-gnu (64-bit)"
 - attr(*, "dimensions")= int [1:3] 1 1 540
  Index:  Date[1:540], format: "1961-01-01" "1961-02-01" "1961-03-01" "1961-04-01" ...

**Comment by javakh** [comment]
access 1.0 or access 1.3 did not give any error to me also but
bcc1_1,bnu-esm,ccsm 4,cesm-bcg and many other cmip5 models are giving
error or 'na' values. Plz kindly check with these models.

**Comment by abdelkaderm** [comment]
Hi !
Yes, you were right, there was a bug in `regrid`,  It is fixed now, please reinstall the package ! 
Many thanks for your help :+1:

**Comment by javakh** [comment]
okay sir...i'll reinstall it...thank u also for giving importance to my query.

**Comment by javakh** [comment]
plz give me the download link of the modified version of the esd package.

**Comment by abdelkaderm** [comment]
it is on Github ! 

Please check https://github.com/metno/esd/wiki/0.-How-to-install%3F

**Comment by javakh** [comment]
Thanks..........It's working now.......
