### ISSUE TITLE
Storm tracks and trajectories

### ISSUE THREAD

**Issue by brasmus** [metno/esd#76]
Perhaps it may be possible to use same methods and class for ice bergs as for storm tracks? And rename the class as 'trajectory'?

**Comment by kajsamp** [comment]
Yes that should be possible. The 'trajectory' class may have even more applications that we haven't considered. Do you have any example of ice berg trajectory data?

**Comment by brasmus** [comment]
We may get some for the Barents Sea and the AACA report.

**Comment by abdelkaderm** [comment]
Sounds interesting :+1:
