### ISSUE TITLE
is esd master available in .tar.gz format?

### ISSUE THREAD

**Issue by monamidutta** [metno/esd#78]
esd master zip is available in .zip. Is it available .tar.gz for Ubuntu, or any other source from where i can get it for installing in Ubuntu?

**Comment by brasmus** [comment]
You can install it from zip as well, but the simplest is to install 'devtools' and then use ```r2 install_github('metno/esd')```. I think you can also use ```r2 install.packages('esd-master.zipp',repos=NULL)```. Another solution is to use unzip in Ubuntu and install from the directory: R CMD INSTALL esd-master.

**Comment by monamidutta** [comment]
Thank you sir. In new esd master regrid() (regrid function) seems to work well.
