### ISSUE TITLE
DS with list predictor

### ISSUE THREAD

**Issue by kajsamp** [metno/esd#79]
The function DS.list is not working. Here's an example (example 5.1 in the esd report):
```r
> data(eof.slp.NCEP)
> data(eof.t2m.NCEP)
> data(Oslo)
> z <- DS(Oslo,list(slp=eof.slp.NCEP,t2m=eof.2tm.NCEP))
Error in inherits(X, "eof") : object 'eof.2tm.NCEP' not found
```

**Comment by kajsamp** [comment]
I've identified the problem. A part of the code had been replaced with as.eof.list (line 882 of DS.R), but the replacement doesn't give us all the necessary output. More specifically, uvd (which was calculated in the replaced code) is not defined which becomes a problem when it is used later in the script.  

For now I've reverted to the old code. It works but isn't as pretty.

**Comment by brasmus** [comment]
Try ```r2 z <- DS(Oslo,list(slp=eof.slp.NCEP,t2m=eof.t2m.NCEP))``` (miss-spelled variable name). The bug is now fixed.

**Comment by kajsamp** [comment]
Oops, that first example didn't show the actual problem, only the miss-spelled variable name. Seems like you solved it anyway :)
