### ISSUE TITLE
DSE.metno does not work

### ISSUE THREAD

**Issue by anitavd** [metno/esd#81]
I tried using DSE.metno but got the following error:
Error: could not find function "DSE.metno"
It is implemented in the help-file though (opens help text when I do ?DSE.metno),
however, x in DSE.metno(x,...) is not listed/explained under Arguments

**Comment by abdelkaderm** [comment]
Hi Anita. This is unfinished function. I started it few moths ago and did not finished it. I will look have a look at it. Actually, we are still running several functions in parallel and we are not decided yet which ones to keep and which ones to keep. Bit it is good that you mentioned these issues. In the meantime you can try DSensemble which is equivalent. e.g. DSensemble(sac=`metnod',...) which will produce seasonal estimates.

**Comment by anitavd** [comment]
Ok, I think I'll wait for your help :-) I get some errors with DSensemble too

**Comment by brasmus** [comment]
DSE is old. Now we use DSensemble together with PCA for describing the predictand as described in Benestad, R.E., D. Chen, A. Mezghani, L. Fan, K. Parding, On using principal components to represent stations in empirical-statistical downscaling, Tellus A 2015, 67, 28326, http://dx.doi.org/10.3402/tellusa.v67.28326
