### ISSUE TITLE
PCA error message

### ISSUE THREAD

**Issue by monamidutta** [metno/esd#82]
When i am doing pca <- PCA(stn)
Where stn are stationdata (81 stations having no missing values) with time period from 1979:1995
then error coming as
Error in pca$u[, 1:neofs] : subscript out of bounds
but when i am extending the time period up to 1999 that means now the time period is from 1979:1999 period, PCA is working properly and not giving any error message.
Is PCA some what time sensitive or its not working below 20 years?

**Comment by kajsamp** [comment]
You can use PCA on the shorter time series but with a smaller number of EOFs, try for example PCA(stn,neofs=5). The number of EOFs (neofs) has to be smaller than or equal to the length of the time series.

**Comment by monamidutta** [comment]
Thank you. Its working
