### ISSUE TITLE
Error is DS

### ISSUE THREAD

**Issue by monamidutta** [metno/esd#85]
I am running DS for 11 year from 1996- 2006 for December month.
ds <-  DS(stn,eof)
where stn is single station and eof is EOF of predictor from ERAINT with same time period.
Error showing as:
Error in step(MODEL, trace = 0) : 
  AIC is -infinity for this model, so 'step' cannot proceed.
Need help

**Comment by abdelkaderm** [comment]
Hi Monami, 

11 years are very short and the estimated parameters are not robust. That's why the regression failed. You need longer time series. Try it with a small number of eofs ?
