### ISSUE TITLE
Problem in 'predict.ds' function

### ISSUE THREAD

**Issue by javakh** [metno/esd#86]
I have taken 'era.t2m' data set for the period '1979-2014'. My station data is in the time period 1979-95. Now using DS function i get downscaled values for  '1979-95' which is expected. But I use predict.ds function on the previously obtained ds results. It should give downscaled values for '1979-2014'.But instead it is giving values for '1979-95' only.This is unexpected.

> str(era)
‘zoo’ series from 1979-01-01 to 2014-10-01
  Data: num [1:430, 1:4374] 4.82 4.98 4.99 3.49 3.24 ...
 sta_cal<-subset(sta,it=1979:1995)
> str(sta_cal)
‘zoo’ series from 1979-01-01 to 1995-12-01
  Data: atomic [1:204] 27.1 25.6 22.3 20.3 20.8 ...
 - attr(*, "location")= chr "SALTA AERO"
 - attr(*, "country")= chr "Argentina"

![ds](https://cloud.githubusercontent.com/assets/11016843/7763856/fba4ff5a-0064-11e5-829a-2148ab931849.jpg)

**Comment by abdelkaderm** [comment]
I am out of office today. can you post your issues on Github so other colleagues can provide you an answer as well. Bests.
----- Original Message -----

**Comment by javakh** [comment]
I have posted it on 'Github'.

Thanks.

**Comment by abdelkaderm** [comment]
Hi Javed, 

The calibration is based on the predictor so the eof in this case.  You have to specify the `newdata` argument which contains the new data sets on which the prediction is made. You need to write the following command
 
```r
ds.pre <- predict.ds(era.ds,newdata=eof)
```
