### ISSUE TITLE
map.station FUN argument

### ISSUE THREAD

**Issue by brasmus** [metno/esd#90]
The call does not take the function FUN.

![screenshot from 2015-06-02 18 22 38](https://cloud.githubusercontent.com/assets/7392034/7940958/6d7c7fe8-0954-11e5-9bbe-f55971d51d59.png)

also, we could introduce the option for the argument 'cex=nv' that automatically sizes the symbol according to number of valid data points.

**Comment by brasmus** [comment]
```
> map(pca)
Warning message:
In plot.xy(xy.coords(x, y), type = type, ...) :
  supplied color is neither numeric nor character
```

**Comment by abdelkaderm** [comment]
in progress ...

**Comment by abdelkaderm** [comment]
Fixed !
