### ISSUE TITLE
How to change the range in color bar when using map() function???

### ISSUE THREAD

**Issue by javakh** [metno/esd#91]
![untitled](https://cloud.githubusercontent.com/assets/11016843/8002280/0c5c58b2-0b8b-11e5-8180-ac6617e97cfe.jpg)

For example....... here the range in the color bar is 0-400. But if I want to change this range as 0-300 or 0-500, what I have to do?????

Thanks

**Comment by abdelkaderm** [comment]
Hi, can you send the command you used to produce the map !

**Comment by javakh** [comment]
Thanks sir.

I have used only : map(x)
