### ISSUE TITLE
Retrieving some GCM results in CMIP5

### ISSUE THREAD

**Issue by brasmus** [metno/esd#92]
Due to some recent changes in retrieve, a bug seems to have snuk into the code. I think it's related to the use of different calendars in different GCMs (We have struggeled with this before). 

Example: the time step of monthly results from BCC-CSM1-1 is 30 days or 31 days most of the time, but sometimes incorrectly 0 or 61 days. This has an effect on the different seasons.

There is a test script in the demo folder: `testgcm.R`

```r2
bcc-csm1-1 . Max T(2m) diff. 19.8876240024339 min time step 0 max time step 61
```

![screenshot from 2015-06-19 13 58 01](https://cloud.githubusercontent.com/assets/7392034/8252983/6aab75c8-168b-11e5-94df-df0e59c4b09f.png)

**Comment by brasmus** [comment]
Quick fix:

```r2
retrieve <- function(x,...) {
  require(ncdf4)
  y <- retrieve.ncdf4(x,...)
  return(y)
}
```

**Comment by brasmus** [comment]
Another solution is to set the argument 'type="ncdf4"', but this requires the ncdf4-library (sorry Windows-users!).

**Comment by abdelkaderm** [comment]
Yes, definitely. There was a bug in `retreive()` function due to the use of different calendars when producing model results. It has been fixed ! People using `ncdf4` were not affected by this,
Bests,
