### ISSUE TITLE
esd installing error

### ISSUE THREAD

**Issue by monamidutta** [metno/esd#93]
Installing esd in windows for 64 bit showing this error:
devtools installed and is in library

library("devtools")
install_github('metno/esd')
Error
Installing github repo(s) metno/esd/master from hadley
Downloading metno/esd.zip from https://github.com/hadley/metno/esd/archive/master.zip
Error: client error: (404) Not Found
How to fix it????

**Comment by abdelkaderm** [comment]
hi Monami,

Have you tried other different installation methods ? For instance, try downloading the package as zip file (in the right of the main github page (https://github.com/metno/esd, there is an item called 'Download ZIP') and install it from R menu bar 'Install package from zip file'.

**Comment by monamidutta** [comment]
yes sir i tried and it worked, i am very sorry for so late comment.
