### ISSUE TITLE
Problem with 'DS' command

### ISSUE THREAD

**Issue by MeJitendra** [metno/esd#95]
Respected Sir,
Today I installed the new version of ESD and was trying to do downscaling using the 'DS' command
I found two errors.
1. In the pdf file of ESD, the jan month is written as jan but it should be inside commas (' ') like 'jan'
![screenshot from 2015-06-28 20 48 21](https://cloud.githubusercontent.com/assets/11473497/8396956/c9706c40-1dd8-11e5-8628-c225a1e27629.png)

2. The plot(ds) command is giving error as follows shown in the figure. I tried for stations over India also and found the same problem.
Error in col[1] : object of type 'closure' is not subsettable
![screenshot from 2015-06-28 20 54 39](https://cloud.githubusercontent.com/assets/11473497/8396960/d0caf3d4-1dd8-11e5-9b86-4f2c5b80eb7c.png)

**Comment by abdelkaderm** [comment]
Hi Jitendra, 
Please reinstall the package to load the recent updates. Must be working again now :+1: 
Bests,
