### ISSUE TITLE
error when plotting a dsensemble object

### ISSUE THREAD

**Issue by anitavd** [metno/esd#97]
I'm trying to plot the results from a DSensemble analysis at Tromsø station (a dsensemble / zoo object), with the command plot(dse.mt2m.rcp85.TROMSØ). I get "Error in plot.new() : figure margins too large"

**Comment by brasmus** [comment]
try with ```dev.new()``` before plot. Also, Norwegian characters ('æ','ø','å') may possibly cause problems.

**Comment by anitavd** [comment]
This works for plotting within the R session (although i only get the correct plot when using rstudio, while with ordinary R or gedit R-plugin I get a scatterplot...strange!). It also works when plotting to a pdf, but I get the same error message when trying to plot to a png (using the command png() to open the connection and then plot). Any idea why?

**Comment by anitavd** [comment]
ok, ignore the issue in parethesis, Abdelkader pointet out that it's a good idea to load the esd package first :)

**Comment by anitavd** [comment]
and the he figured out the other problem as well: if I don't specify width and height in the png command, it works.
