### ISSUE TITLE
 plotting several maps in the same plotting window

### ISSUE THREAD

**Issue by javakh** [metno/esd#99]
How to plot several maps in the same plotting window in esd package and how to align the colorbar in vertical direction?
par(mfrow=c(x1,x2)) seems to be not working for map.

Also unable to off the colorbar.
map(data,colorbar=FALSE)
or map(data,colorbar=NULL)
not working.

Thanks for your help.

**Comment by kajsamp** [comment]
You should also be able to add several maps to one window by using new=FALSE but it is not working. In the following example I expect the second map to be added next to the first one but instead I get a new window. 

data <- t2m.NCEP(lon=c(-30,30),lat=c(40,70))
par(fig=c(0,0.5,0.2,0.8))
map(data,FUN='mean')
par(fig=c(0.5,1.0,0.2,0.8))
map(data,FUN='max',new=FALSE)

Regarding the colorbar, you can plot a map without a colorbar like this:
map(data,colbar=list(show=FALSE))

**Comment by javakh** [comment]
Thanks for your suggestion. i'll try this.

**Comment by javakh** [comment]
map(data,FUN='max',new=FALSE)

This is not working
